package sim

import (
	"math"

	enginev1 "github.com/aressim/internal/gen/engine/v1"
)

// processTick advances all active units with move orders by one tick and
// returns a UnitDelta for every unit that changed position or order state.
// timeScale multiplies how many sim-seconds of movement occur per real second.
func processTick(units []*enginev1.Unit, defs map[string]DefStats, timeScale float64) []*enginev1.UnitDelta {
	deltas := make([]*enginev1.UnitDelta, 0, len(units))
	unitByID := make(map[string]*enginev1.Unit, len(units))
	for _, unit := range units {
		unitByID[unit.GetId()] = unit
	}

	for _, u := range units {
		if !unitCanOperate(u) {
			continue
		}
		pos := u.GetPosition()
		if pos == nil {
			continue
		}
		status := u.GetStatus()
		if status == nil {
			status = &enginev1.OperationalStatus{IsActive: true}
			u.Status = status
		}

		def := defs[normalizeDefinitionID(u.GetDefinitionId())]
		order := u.GetMoveOrder()
		hasMoveOrder := order != nil && len(order.Waypoints) > 0
		airborne := isAirborneAircraft(u, def)
		if !hasMoveOrder && !airborne {
			continue
		}

		cruiseSpeed := def.CruiseSpeedMps
		if cruiseSpeed <= 0 {
			cruiseSpeed = 10
		}

		var wp *enginev1.Waypoint
		distM := 0.0
		canMoveM := 0.0
		if hasMoveOrder {
			wp = order.Waypoints[0]
			distM = haversineM(pos.Lat, pos.Lon, wp.Lat, wp.Lon)
			canMoveM = cruiseSpeed * tickInterval.Seconds() * timeScale
		}

		fuelBurnLiters := tickFuelBurnLiters(u, def, timeScale)
		if fuelBurnLiters > 0 {
			currentFuel := float64(status.GetFuelLevelLiters())
			if currentFuel <= 0 {
				canMoveM = 0
				fuelBurnLiters = 0
			} else if hasMoveOrder && currentFuel < fuelBurnLiters {
				canMoveM *= currentFuel / fuelBurnLiters
				fuelBurnLiters = currentFuel
			} else if currentFuel < fuelBurnLiters {
				fuelBurnLiters = currentFuel
			}
		}

		newLat, newLon := pos.Lat, pos.Lon
		var remainingWaypoints []*enginev1.Waypoint

		if hasMoveOrder {
			if canMoveM >= distM {
				newLat = wp.Lat
				newLon = wp.Lon
				remainingWaypoints = order.Waypoints[1:]
			} else {
				brng := bearingRad(pos.Lat, pos.Lon, wp.Lat, wp.Lon)
				newLat, newLon = movePoint(pos.Lat, pos.Lon, brng, canMoveM)
				remainingWaypoints = order.Waypoints
			}
		}

		newHeading := pos.Heading
		if len(remainingWaypoints) > 0 {
			target := remainingWaypoints[0]
			newHeading = BearingDeg(newLat, newLon, target.Lat, target.Lon)
		}

		newSpeed := 0.0
		var newOrder *enginev1.MoveOrder
		if len(remainingWaypoints) > 0 {
			newSpeed = cruiseSpeed
			newOrder = &enginev1.MoveOrder{
				Waypoints:     remainingWaypoints,
				AutoGenerated: order.GetAutoGenerated(),
			}
		} else if hasMoveOrder {
			newOrder = &enginev1.MoveOrder{AutoGenerated: order.GetAutoGenerated()}
		}

		altMsl := pos.GetAltMsl()
		if hasMoveOrder {
			altMsl = TravelAltitudeM(u, def)
		}
		if hasMoveOrder && len(remainingWaypoints) == 0 && shouldLandAtHostBase(u, unitByID, newLat, newLon) {
			host := unitByID[u.GetHostBaseId()]
			newLat = host.GetPosition().GetLat()
			newLon = host.GetPosition().GetLon()
			altMsl = host.GetPosition().GetAltMsl()
			newHeading = host.GetPosition().GetHeading()
			newSpeed = 0
		}

		u.Position = &enginev1.Position{
			Lat:     newLat,
			Lon:     newLon,
			AltMsl:  altMsl,
			Heading: newHeading,
			Speed:   newSpeed,
		}
		u.MoveOrder = newOrder
		if fuelBurnLiters > 0 {
			status.FuelLevelLiters = float32(math.Max(0, float64(status.GetFuelLevelLiters())-fuelBurnLiters))
		}
		fuelExhausted := status.GetFuelLevelLiters() <= 0 && def.FuelBurnRateLph > 0
		if fuelExhausted && airborne {
			status.IsActive = false
			status.CombatEffectiveness = 0
			u.DamageState = enginev1.DamageState_DAMAGE_STATE_MISSION_KILLED
			u.MoveOrder = nil
			u.Position.Speed = 0
			newOrder = &enginev1.MoveOrder{}
		}

		delta := &enginev1.UnitDelta{
			UnitId:    u.Id,
			Position:  u.Position,
			MoveOrder: newOrder,
		}
		if fuelBurnLiters > 0 || fuelExhausted {
			delta.Status = status
			delta.DamageState = u.GetDamageState()
		}
		deltas = append(deltas, delta)
	}

	deltas = append(deltas, syncHostedAircraftToHostBases(units, defs)...)
	return deltas
}
