package sim

import (
	"math"
	"strings"

	"github.com/aressim/internal/geo"
	enginev1 "github.com/aressim/internal/gen/engine/v1"
)

func processBehaviorTick(units []*enginev1.Unit, defs map[string]DefStats, weapons map[string]WeaponStats, simSeconds float64) []*enginev1.UnitDelta {
	tracks := buildTrackPicture(units, defs, nil, nil, fixedRng(0))
	unitByID := make(map[string]*enginev1.Unit, len(units))
	for _, u := range units {
		unitByID[u.Id] = u
	}

	deltas := make([]*enginev1.UnitDelta, 0)
	for _, u := range units {
		if !unitCanOperate(u) || !unitCanMove(u, defs) {
			continue
		}
		def := defs[normalizeDefinitionID(u.GetDefinitionId())]

		if shouldWithdrawForFuel(u, def, unitByID) {
			waypoint := returnToHostBaseWaypoint(u, def, unitByID)
			if waypoint != nil {
				needsUpdate := u.GetAttackOrder() != nil || returnRouteNeedsUpdate(u, waypoint)
				u.AttackOrder = nil
				if needsUpdate {
					order := &enginev1.MoveOrder{
						Waypoints:     []*enginev1.Waypoint{waypoint},
						AutoGenerated: true,
					}
					u.MoveOrder = order
					deltas = append(deltas, &enginev1.UnitDelta{
						UnitId:    u.Id,
						MoveOrder: order,
					})
				}
			}
			continue
		}

		if shouldWithdrawForPrimaryWeaponDepletion(u, def) {
			waypoint := returnToHostBaseWaypoint(u, def, unitByID)
			if waypoint != nil {
				needsUpdate := u.GetAttackOrder() != nil || returnRouteNeedsUpdate(u, waypoint)
				u.AttackOrder = nil
				if needsUpdate {
					order := &enginev1.MoveOrder{
						Waypoints:     []*enginev1.Waypoint{waypoint},
						AutoGenerated: true,
					}
					u.MoveOrder = order
					deltas = append(deltas, &enginev1.UnitDelta{
						UnitId:    u.Id,
						MoveOrder: order,
					})
				}
			}
			continue
		}

		if hasExplicitAttackOrder(u) {
			order := u.GetAttackOrder()
			target := unitByID[order.GetTargetUnitId()]
			if target == nil || !unitIsAlive(target) || (u.GetAttackOrder().GetOrderType() == enginev1.AttackOrderType_ATTACK_ORDER_TYPE_STRIKE_UNTIL_EFFECT &&
				desiredEffectSatisfied(target, u.GetAttackOrder().GetDesiredEffect())) {
				u.AttackOrder = nil
				var moveOrderDelta *enginev1.MoveOrder
				if current := u.GetMoveOrder(); current != nil && current.GetAutoGenerated() {
					u.MoveOrder = nil
					moveOrderDelta = &enginev1.MoveOrder{}
				}
				deltas = append(deltas, &enginev1.UnitDelta{
					UnitId:    u.Id,
					MoveOrder: moveOrderDelta,
				})
				continue
			}
			waypoint := computeAttackWaypoint(u, target, defs, weapons)
			if waypoint != nil {
				if attackRouteNeedsUpdate(u, waypoint) {
					order := &enginev1.MoveOrder{
						Waypoints:     []*enginev1.Waypoint{waypoint},
						AutoGenerated: true,
					}
					u.MoveOrder = order
					deltas = append(deltas, &enginev1.UnitDelta{
						UnitId:    u.Id,
						MoveOrder: order,
					})
				}
				continue
			}
		}

		if hasExplicitMoveOrder(u) || hasExplicitAttackOrder(u) {
			continue
		}

		target := nearestTrackedEnemy(u, tracks, unitByID)
		if target == nil {
			continue
		}

		var waypoint *enginev1.Waypoint
		switch u.GetEngagementBehavior() {
		case enginev1.EngagementBehavior_ENGAGEMENT_BEHAVIOR_SHADOW_CONTACT:
			waypoint = geo.ProtoWaypoint(
				target.GetPosition().GetLat(),
				target.GetPosition().GetLon(),
				TravelAltitudeM(u, defs[u.DefinitionId]),
			)
		case enginev1.EngagementBehavior_ENGAGEMENT_BEHAVIOR_WITHDRAW_ON_DETECT:
			waypoint = computeWithdrawWaypoint(u, target, defs[u.DefinitionId])
		default:
			continue
		}
		if waypoint == nil {
			continue
		}

		order := &enginev1.MoveOrder{Waypoints: []*enginev1.Waypoint{waypoint}}
		u.MoveOrder = order
		deltas = append(deltas, &enginev1.UnitDelta{
			UnitId:    u.Id,
			MoveOrder: order,
		})
	}
	return deltas
}

func ComputeAttackWaypointForOrder(shooter, target *enginev1.Unit, defs map[string]DefStats, weapons map[string]WeaponStats) *enginev1.Waypoint {
	if shooter == nil || target == nil || shooter.GetPosition() == nil || target.GetPosition() == nil {
		return nil
	}
	targetDef, ok := defs[target.DefinitionId]
	if !ok {
		targetDef, ok = defs[normalizeDefinitionID(target.DefinitionId)]
	}
	if !ok {
		return nil
	}
	_, weapon, hasWeapon := selectBestWeapon(shooter, targetDef.Domain, weapons)
	if !hasWeapon || weapon.RangeM <= 0 {
		return nil
	}
	dist := haversineM(
		shooter.GetPosition().GetLat(), shooter.GetPosition().GetLon(),
		target.GetPosition().GetLat(), target.GetPosition().GetLon(),
	)
	desiredStandOff := weapon.RangeM * 0.85
	if desiredStandOff <= 0 {
		return nil
	}
	if dist <= desiredStandOff {
		return nil
	}
	moveDist := dist - desiredStandOff
	brng := bearingRad(
		shooter.GetPosition().GetLat(), shooter.GetPosition().GetLon(),
		target.GetPosition().GetLat(), target.GetPosition().GetLon(),
	)
	lat, lon := movePoint(shooter.GetPosition().GetLat(), shooter.GetPosition().GetLon(), brng, moveDist)
	shooterDef := defs[normalizeDefinitionID(shooter.DefinitionId)]
	return geo.ProtoWaypoint(lat, lon, TravelAltitudeM(shooter, shooterDef))
}

func CanUnitAttackTarget(shooter, target *enginev1.Unit, defs map[string]DefStats, weapons map[string]WeaponStats) bool {
	if shooter == nil || target == nil || shooter.GetPosition() == nil || target.GetPosition() == nil {
		return false
	}
	targetDef, ok := defs[target.DefinitionId]
	if !ok {
		targetDef, ok = defs[normalizeDefinitionID(target.DefinitionId)]
	}
	if !ok {
		return false
	}
	_, weapon, hasWeapon := selectBestWeapon(shooter, targetDef.Domain, weapons)
	if !hasWeapon || weapon.RangeM <= 0 {
		return false
	}
	dist := haversineM(
		shooter.GetPosition().GetLat(), shooter.GetPosition().GetLon(),
		target.GetPosition().GetLat(), target.GetPosition().GetLon(),
	)
	if dist <= weapon.RangeM {
		return true
	}
	return ComputeAttackWaypointForOrder(shooter, target, defs, weapons) != nil
}

func computeAttackWaypoint(shooter, target *enginev1.Unit, defs map[string]DefStats, weapons map[string]WeaponStats) *enginev1.Waypoint {
	return ComputeAttackWaypointForOrder(shooter, target, defs, weapons)
}

func attackRouteNeedsUpdate(unit *enginev1.Unit, waypoint *enginev1.Waypoint) bool {
	order := unit.GetMoveOrder()
	if order == nil || len(order.GetWaypoints()) == 0 {
		return true
	}
	if !order.GetAutoGenerated() {
		return false
	}
	if len(order.GetWaypoints()) != 1 {
		return true
	}
	current := order.GetWaypoints()[0]
	return haversineM(current.GetLat(), current.GetLon(), waypoint.GetLat(), waypoint.GetLon()) > 5_000
}

func returnRouteNeedsUpdate(unit *enginev1.Unit, waypoint *enginev1.Waypoint) bool {
	order := unit.GetMoveOrder()
	if order == nil || len(order.GetWaypoints()) == 0 {
		return true
	}
	if !order.GetAutoGenerated() || len(order.GetWaypoints()) != 1 {
		return true
	}
	current := order.GetWaypoints()[0]
	return haversineM(current.GetLat(), current.GetLon(), waypoint.GetLat(), waypoint.GetLon()) > 1_000
}

func hasExplicitMoveOrder(u *enginev1.Unit) bool {
	order := u.GetMoveOrder()
	return order != nil && len(order.Waypoints) > 0
}

func hasExplicitAttackOrder(u *enginev1.Unit) bool {
	order := u.GetAttackOrder()
	return order != nil &&
		order.GetOrderType() != enginev1.AttackOrderType_ATTACK_ORDER_TYPE_UNSPECIFIED &&
		order.GetTargetUnitId() != ""
}

func unitCanMove(u *enginev1.Unit, defs map[string]DefStats) bool {
	if u.GetPosition() == nil {
		return false
	}
	return defs[u.DefinitionId].CruiseSpeedMps > 0
}

func shouldWithdrawForFuel(unit *enginev1.Unit, def DefStats, unitByID map[string]*enginev1.Unit) bool {
	if !isAirborneAircraft(unit, def) {
		return false
	}
	requiredFuel := requiredFuelToReachHostBaseLiters(unit, def, unitByID)
	if requiredFuel <= 0 {
		return false
	}
	return float64(unit.GetStatus().GetFuelLevelLiters()) <= requiredFuel*1.10
}

func shouldWithdrawForPrimaryWeaponDepletion(unit *enginev1.Unit, def DefStats) bool {
	if !isAirborneAircraft(unit, def) {
		return false
	}
	if strings.TrimSpace(unit.GetHostBaseId()) == "" {
		return false
	}
	primary := primaryWeaponState(unit)
	if primary == nil {
		return false
	}
	return primary.GetMaxQty() > 0 && primary.GetCurrentQty() <= 0
}

func nearestTrackedEnemy(unit *enginev1.Unit, tracks trackPicture, unitByID map[string]*enginev1.Unit) *enginev1.Unit {
	groupID := tracks.GroupForUnit[unit.Id]
	if groupID == "" {
		return nil
	}
	targets := tracks.ByGroup[groupID]
	var nearest *enginev1.Unit
	bestDist := math.MaxFloat64
	for targetID := range targets {
		target := unitByID[targetID]
		if target == nil || !unitIsAlive(target) || !unitsAreHostile(unit, target) {
			continue
		}
		dist := haversineM(
			unit.GetPosition().GetLat(), unit.GetPosition().GetLon(),
			target.GetPosition().GetLat(), target.GetPosition().GetLon(),
		)
		if dist < bestDist {
			bestDist = dist
			nearest = target
		}
	}
	return nearest
}

func computeWithdrawWaypoint(unit, threat *enginev1.Unit, def DefStats) *enginev1.Waypoint {
	if unit.GetPosition() == nil || threat.GetPosition() == nil {
		return nil
	}
	distance := def.DetectionRangeM * 0.75
	if distance < 20_000 {
		distance = 20_000
	}
	if distance > 150_000 {
		distance = 150_000
	}
	brng := bearingRad(threat.GetPosition().GetLat(), threat.GetPosition().GetLon(), unit.GetPosition().GetLat(), unit.GetPosition().GetLon())
	lat, lon := movePoint(unit.GetPosition().GetLat(), unit.GetPosition().GetLon(), brng, distance)
	return geo.ProtoWaypoint(lat, lon, TravelAltitudeM(unit, def))
}
