/**
 * bridge.ts
 *
 * Wails event bridge: subscribes to sim:* events emitted by the Go backend,
 * decodes base64-encoded proto binaries, and dispatches into the Zustand store.
 */

import { EventsOn } from "../../wailsjs/runtime/runtime";
import {
  useSimStore,
  Unit,
  MoveOrder,
  EventLogEntry,
  WeaponState,
  WeaponDef,
  Munition,
  ExplosionFx,
  DetectionContact,
  CountryRelationship,
  TeamScore,
} from "../store/simStore";
import { fromBinary, type DescMessage } from "@bufbuild/protobuf";

import {
  FullStateSnapshotSchema,
  BatchUnitUpdateSchema,
  ScenarioStateEventSchema,
  UnitSpawnedEventSchema,
  UnitDestroyedEventSchema,
  NarrativeEventSchema,
  DetectionUpdateSchema,
  MunitionUpdateSchema,
} from "@proto/engine/v1/events_pb";
import type {
  FullStateSnapshot,
  BatchUnitUpdate,
  ScenarioStateEvent,
  UnitSpawnedEvent,
  UnitDestroyedEvent,
  NarrativeEvent,
  DetectionUpdate,
  MunitionUpdate,
  UnitDelta,
  TeamScore as ProtoTeamScore,
} from "@proto/engine/v1/events_pb";
import type { Unit as ProtoUnit } from "@proto/engine/v1/unit_pb";
import type { WeaponDefinition as ProtoWeaponDef } from "@proto/engine/v1/weapon_pb";
import type { MoveOrder as ProtoMoveOrder } from "@proto/engine/v1/common_pb";
import type { OperationalStatus } from "@proto/engine/v1/status_pb";
import { ScenarioPlayState } from "@proto/engine/v1/events_pb";

// ─── HELPERS ─────────────────────────────────────────────────────────────────

function b64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function decodeProtoEvent<T>(schema: DescMessage, eventName: string, b64: string): T | null {
  try {
    return fromBinary(schema, b64ToBytes(b64)) as T;
  } catch (error) {
    console.error(`[bridge] ${eventName} decode failed`, error);
    return null;
  }
}

function registerProtoEvent<T>(
  eventName: string,
  schema: DescMessage,
  handler: (message: T) => void,
): void {
  EventsOn(eventName, (b64: string) => {
    const message = decodeProtoEvent<T>(schema, eventName.replace("sim:", ""), b64);
    if (!message) {
      return;
    }
    handler(message);
  });
}

// ─── PROTO → STORE CONVERTERS ─────────────────────────────────────────────────

function protoMoveOrderToStore(m: ProtoMoveOrder | undefined): MoveOrder | undefined {
  if (!m) return undefined;
  return {
    autoGenerated: m.autoGenerated,
    waypoints: m.waypoints.map((wp) => ({
      lat: wp.lat,
      lon: wp.lon,
      altMsl: wp.altMsl,
    })),
  };
}

function protoStatusToStore(s?: OperationalStatus): Unit["status"] {
  return {
    personnelStrength: s?.personnelStrength ?? 1,
    equipmentStrength: s?.equipmentStrength ?? 1,
    combatEffectiveness: s?.combatEffectiveness ?? 1,
    fuelLevelLiters: s?.fuelLevelLiters ?? 0,
    morale: s?.morale ?? 1,
    fatigue: s?.fatigue ?? 0,
    isActive: s?.isActive ?? true,
    suppressed: false,
    disrupted: false,
    routing: false,
  };
}

export function protoUnitToStore(u: ProtoUnit): Unit {
  return {
    id: u.id,
    displayName: u.displayName,
    fullName: u.fullName,
    side: u.side,
    teamId: u.teamId || undefined,
    coalitionId: u.coalitionId || undefined,
    natoPendingSymbol: u.natoSymbolSidc,
    definitionId: u.definitionId,
    hostBaseId: u.hostBaseId || undefined,
    loadoutConfigurationId: u.loadoutConfigurationId || undefined,
    damageState: u.damageState || 1,
    nextSortieReadySeconds: u.nextSortieReadySeconds || 0,
    nextStrikeReadySeconds: u.nextStrikeReadySeconds || 0,
    baseOps: u.baseOps
      ? {
          state: u.baseOps.state,
          nextLaunchAvailableSeconds: u.baseOps.nextLaunchAvailableSeconds,
          nextRecoveryAvailableSeconds: u.baseOps.nextRecoveryAvailableSeconds,
        }
      : undefined,
    engagementBehavior: u.engagementBehavior || 1,
    engagementPkillThreshold: u.engagementPkillThreshold || 0.5,
    attackOrder: u.attackOrder
      ? {
          orderType: u.attackOrder.orderType,
          targetUnitId: u.attackOrder.targetUnitId,
          desiredEffect: u.attackOrder.desiredEffect,
          pkillThreshold: u.attackOrder.pkillThreshold,
        }
      : undefined,
    position: {
      lat: u.position?.lat ?? 0,
      lon: u.position?.lon ?? 0,
      altMsl: u.position?.altMsl ?? 0,
      heading: u.position?.heading ?? 0,
      speed: u.position?.speed ?? 0,
    },
    status: protoStatusToStore(u.status),
    parentUnitId: u.parentUnitId || undefined,
    moveOrder: protoMoveOrderToStore(u.moveOrder),
    weapons: (u.weapons ?? []).map((w): WeaponState => ({
      weaponId: w.weaponId,
      currentQty: w.currentQty,
      maxQty: w.maxQty,
    })),
  };
}

function protoWeaponDefToStore(w: ProtoWeaponDef): WeaponDef {
  return {
    id: w.id,
    name: w.name,
    description: w.description,
    domainTargets: w.domainTargets,
    speedMps: w.speedMps,
    rangeM: w.rangeM,
    probabilityOfHit: w.probabilityOfHit,
    effectType: w.effectType,
  };
}

function protoTeamScoreToStore(score: ProtoTeamScore): TeamScore {
  return {
    teamId: score.teamId,
    replacementLossUsd: score.replacementLossUsd,
    strategicLossUsd: score.strategicLossUsd,
    economicLossUsd: score.economicLossUsd,
    humanLossUsd: score.humanLossUsd,
    totalLossUsd: score.totalLossUsd,
  };
}

function applyDelta(delta: UnitDelta): void {
  const store = useSimStore.getState();
  const patch: Partial<Unit> = {};

  if (delta.position) {
    patch.position = {
      lat: delta.position.lat,
      lon: delta.position.lon,
      altMsl: delta.position.altMsl,
      heading: delta.position.heading,
      speed: delta.position.speed,
    };
  }
  if (delta.status) {
    patch.status = protoStatusToStore(delta.status);
  }
  if (delta.damageState !== 0) {
    patch.damageState = delta.damageState;
  }
  if (delta.nextSortieReadySeconds !== 0) {
    patch.nextSortieReadySeconds = delta.nextSortieReadySeconds;
  }
  if (delta.nextStrikeReadySeconds !== 0) {
    patch.nextStrikeReadySeconds = delta.nextStrikeReadySeconds;
  }
  if (delta.baseOps) {
    patch.baseOps = {
      state: delta.baseOps.state,
      nextLaunchAvailableSeconds: delta.baseOps.nextLaunchAvailableSeconds,
      nextRecoveryAvailableSeconds: delta.baseOps.nextRecoveryAvailableSeconds,
    };
  }
  // moveOrder present in delta = update (empty waypoints = clear order)
  if (delta.moveOrder !== undefined) {
    patch.moveOrder = delta.moveOrder.waypoints.length > 0
      ? protoMoveOrderToStore(delta.moveOrder)
      : undefined;
  }
  // weapon states present = ammo changed (adjudicator fired a weapon)
  if (delta.weapons && delta.weapons.length > 0) {
    patch.weapons = delta.weapons.map((w): WeaponState => ({
      weaponId: w.weaponId,
      currentQty: w.currentQty,
      maxQty: w.maxQty,
    }));
  }

  store.applyUnitDelta(delta.unitId, patch);
}

function queueExplosionRemoval(id: string, durationMs: number): void {
  window.setTimeout(() => {
    useSimStore.getState().removeExplosion(id);
  }, durationMs);
}

function spawnExplosion(
  lat: number,
  lon: number,
  altMsl: number,
  kind: ExplosionFx["kind"],
  durationMs: number,
): void {
  const id = `${kind}_${crypto.randomUUID()}`;
  useSimStore.getState().addExplosion({ id, lat, lon, altMsl, kind });
  queueExplosionRemoval(id, durationMs);
}

export function protoEventToLogEntry(e: NarrativeEvent, simSeconds: number): EventLogEntry {
  return {
    id: crypto.randomUUID(),
    text: e.text,
    category: e.category,
    unitId: e.unitId,
    side: e.side,
    simSeconds,
  };
}

// ─── EVENT SUBSCRIPTIONS ─────────────────────────────────────────────────────

export function initBridge(): void {
  const store = useSimStore.getState();

  // ── Full state snapshot ────────────────────────────────────────────────────
  registerProtoEvent<FullStateSnapshot>("sim:full_state_snapshot", FullStateSnapshotSchema, (snap) => {
    const units = snap.units.map(protoUnitToStore);
    const weaponDefs = snap.weaponDefinitions.map(protoWeaponDefToStore);
    const relationships: CountryRelationship[] = snap.relationships.map((rel) => ({
      fromCountry: rel.fromCountry,
      toCountry: rel.toCountry,
      shareIntel: rel.shareIntel,
      airspaceTransitAllowed: rel.airspaceTransitAllowed,
      airspaceStrikeAllowed: rel.airspaceStrikeAllowed,
      defensivePositioningAllowed: rel.defensivePositioningAllowed,
      maritimeTransitAllowed: rel.maritimeTransitAllowed,
      maritimeStrikeAllowed: rel.maritimeStrikeAllowed,
    }));
    const scores: TeamScore[] = snap.scores.map(protoTeamScoreToStore);
    store.loadSnapshot(units, snap.scenarioName, weaponDefs, relationships, scores);
    if (snap.simTime) {
      store.setSimTime(snap.simTime.secondsElapsed, Number(snap.simTime.tickNumber));
    }
    console.log(`[bridge] snapshot loaded: ${units.length} units, ${weaponDefs.length} weapon defs, scenario="${snap.scenarioName}"`);
  });

  // ── Per-tick batch update ──────────────────────────────────────────────────
  registerProtoEvent<BatchUnitUpdate>("sim:batch_update", BatchUnitUpdateSchema, (msg) => {
    for (const delta of msg.deltas) {
      applyDelta(delta);
    }
    if (msg.scores.length > 0) {
      store.setScores(msg.scores.map(protoTeamScoreToStore));
    }
    if (msg.simTime) {
      store.setSimTime(msg.simTime.secondsElapsed, Number(msg.simTime.tickNumber));
    }
  });

  // ── Unit lifecycle ─────────────────────────────────────────────────────────
  registerProtoEvent<UnitSpawnedEvent>("sim:unit_spawned", UnitSpawnedEventSchema, (ev) => {
    if (ev.unit) store.spawnUnit(protoUnitToStore(ev.unit));
  });

  registerProtoEvent<UnitDestroyedEvent>("sim:unit_destroyed", UnitDestroyedEventSchema, (ev) => {
    const destroyed = useSimStore.getState().units.get(ev.unitId);
    if (destroyed) {
      spawnExplosion(
        destroyed.position.lat,
        destroyed.position.lon,
        destroyed.position.altMsl,
        "kill",
        1400,
      );
    }
    store.destroyUnit(ev.unitId);
  });

  // ── Scenario state ─────────────────────────────────────────────────────────
  registerProtoEvent<ScenarioStateEvent>("sim:scenario_state", ScenarioStateEventSchema, (ev) => {
    const stateMap = {
      [ScenarioPlayState.SCENARIO_UNSPECIFIED]: "idle",
      [ScenarioPlayState.SCENARIO_PAUSED]: "paused",
      [ScenarioPlayState.SCENARIO_RUNNING]: "running",
      [ScenarioPlayState.SCENARIO_ENDED]: "ended",
    } as const;
    store.setScenarioState(stateMap[ev.state] ?? "idle", ev.timeScale);
  });

  // ── Narrative event log ────────────────────────────────────────────────────
  registerProtoEvent<NarrativeEvent>("sim:narrative", NarrativeEventSchema, (ev) => {
    const { simSeconds } = useSimStore.getState();
    store.appendEventLog(protoEventToLogEntry(ev, simSeconds));
  });

  // ── Sensor detection updates ───────────────────────────────────────────
  registerProtoEvent<DetectionUpdate>("sim:detection_update", DetectionUpdateSchema, (ev) => {
    const contacts: DetectionContact[] = ev.unitContacts.map((contact) => ({
      unitId: contact.unitId,
      sourceTeam: contact.sourceTeam,
      shared: contact.shared,
    }));
    store.setDetections(ev.detectingSide, ev.detectedUnitIds, contacts);
    store.setMunitionDetections(ev.detectingSide, ev.detectedMunitionIds);
  });

  // ── In-flight munition update ──────────────────────────────────────────
  registerProtoEvent<MunitionUpdate>("sim:munition_update", MunitionUpdateSchema, (ev) => {
    const previous = useSimStore.getState().munitions;
    const munitions: Munition[] = ev.munitions.map((m) => ({
      id: m.id,
      weaponId: m.weaponId,
      shooterId: m.shooterId,
      lat: m.position?.lat ?? 0,
      lon: m.position?.lon ?? 0,
      altMsl: m.position?.altMsl ?? 0,
    }));
    const nextIds = new Set(munitions.map((m) => m.id));
    previous.forEach((munition, id) => {
      if (!nextIds.has(id)) {
        spawnExplosion(munition.lat, munition.lon, munition.altMsl, "impact", 700);
      }
    });
    store.setMunitions(munitions);
  });

  console.log("[bridge] event listeners registered");
}
