package scenario

import enginev1 "github.com/aressim/internal/gen/engine/v1"

// DefaultUnitDefinitions returns a starter library of unit definitions.
// These are seeded into the database on first launch.
func DefaultUnitDefinitions() []*enginev1.UnitDefinition {
	return []*enginev1.UnitDefinition{
		// ── Land — Armour & Mechanised ─────────────────────────────────────────
		{
			Id: "mbt-m1a2-abrams", Name: "M1A2 SEPv3 Abrams", Description: "US Army main battle tank",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_TRACKED_VEHICLE,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_MAIN_BATTLE_TANK, SpecificType: "M1A2 SEPv3 Abrams",
			NationOfOrigin: "USA", ServiceEntryYear: 1980,
			BaseStrength: 0.95, CombatRangeM: 3500, Accuracy: 0.85,
			MaxSpeedMps: 17.9, CruiseSpeedMps: 10.0, MaxRangeKm: 465,
			Survivability: 0.80, DetectionRangeM: 4000,
			FuelCapacityLiters: 1907, FuelBurnRateLph: 378,
		},
		{
			Id: "ifv-m2a3-bradley", Name: "M2A3 Bradley", Description: "US Army infantry fighting vehicle",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_TRACKED_VEHICLE,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_INFANTRY_FIGHTING_VEHICLE, SpecificType: "M2A3 Bradley",
			NationOfOrigin: "USA", ServiceEntryYear: 1981,
			BaseStrength: 0.75, CombatRangeM: 2500, Accuracy: 0.80,
			MaxSpeedMps: 10.0, CruiseSpeedMps: 6.7, MaxRangeKm: 480,
			Survivability: 0.65, DetectionRangeM: 3000,
			FuelCapacityLiters: 662, FuelBurnRateLph: 150,
		},
		{
			Id: "recon-m1127-stryker", Name: "M1127 Stryker RV", Description: "US Army wheeled reconnaissance vehicle",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_WHEELED_VEHICLE,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_RECONNAISSANCE_VEHICLE, SpecificType: "M1127 Stryker RV",
			NationOfOrigin: "USA", ServiceEntryYear: 2002,
			BaseStrength: 0.60, CombatRangeM: 1500, Accuracy: 0.70,
			MaxSpeedMps: 22.2, CruiseSpeedMps: 16.7, MaxRangeKm: 500,
			Survivability: 0.50, DetectionRangeM: 5000,
			FuelCapacityLiters: 200, FuelBurnRateLph: 60,
		},
		// ── Land — Fires ────────────────────────────────────────────────────────
		{
			Id: "artillery-sp-m109a7", Name: "M109A7 Paladin", Description: "US Army self-propelled 155mm howitzer",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_TRACKED_VEHICLE,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_SELF_PROPELLED_ARTILLERY, SpecificType: "M109A7 Paladin",
			NationOfOrigin: "USA", ServiceEntryYear: 1963,
			BaseStrength: 0.70, CombatRangeM: 30000, Accuracy: 0.75,
			MaxSpeedMps: 10.6, CruiseSpeedMps: 8.0, MaxRangeKm: 350,
			Survivability: 0.45, DetectionRangeM: 1000,
			FuelCapacityLiters: 511, FuelBurnRateLph: 120,
		},
		{
			Id: "artillery-towed-m777", Name: "M777 Howitzer", Description: "Lightweight 155mm towed howitzer",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_TOWED_SYSTEM,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_TOWED_ARTILLERY, SpecificType: "M777A2",
			NationOfOrigin: "USA", ServiceEntryYear: 2005,
			BaseStrength: 0.65, CombatRangeM: 30000, Accuracy: 0.78,
			MaxSpeedMps: 0, CruiseSpeedMps: 0, MaxRangeKm: 0,
			Survivability: 0.25, DetectionRangeM: 800,
			FuelCapacityLiters: 0, FuelBurnRateLph: 0,
		},
		{
			Id: "mlrs-m270", Name: "M270 MLRS", Description: "Multiple launch rocket system",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_TRACKED_VEHICLE,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_ROCKET_ARTILLERY, SpecificType: "M270A2 MLRS",
			NationOfOrigin: "USA", ServiceEntryYear: 1983,
			BaseStrength: 0.80, CombatRangeM: 84000, Accuracy: 0.70,
			MaxSpeedMps: 16.1, CruiseSpeedMps: 11.1, MaxRangeKm: 480,
			Survivability: 0.40, DetectionRangeM: 1500,
			FuelCapacityLiters: 617, FuelBurnRateLph: 140,
		},
		// ── Land — Infantry ─────────────────────────────────────────────────────
		{
			Id: "infantry-light", Name: "Light Infantry", Description: "Standard light infantry unit",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_DISMOUNTED_INFANTRY,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_LIGHT_INFANTRY, SpecificType: "Light Infantry",
			NationOfOrigin: "USA", ServiceEntryYear: 1900,
			BaseStrength: 0.60, CombatRangeM: 500, Accuracy: 0.65,
			MaxSpeedMps: 1.4, CruiseSpeedMps: 1.0, MaxRangeKm: 40,
			Survivability: 0.40, DetectionRangeM: 800,
			FuelCapacityLiters: 0, FuelBurnRateLph: 0,
		},
		{
			Id: "infantry-airborne", Name: "Airborne Infantry", Description: "Parachute-capable light infantry",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_DISMOUNTED_INFANTRY,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_AIRBORNE_INFANTRY, SpecificType: "Airborne Infantry",
			NationOfOrigin: "USA", ServiceEntryYear: 1940,
			BaseStrength: 0.65, CombatRangeM: 500, Accuracy: 0.68,
			MaxSpeedMps: 1.4, CruiseSpeedMps: 1.0, MaxRangeKm: 40,
			Survivability: 0.38, DetectionRangeM: 900,
			FuelCapacityLiters: 0, FuelBurnRateLph: 0,
		},
		{
			Id: "infantry-special-forces", Name: "Army Special Forces ODA", Description: "12-man special forces operational detachment",
			Domain: enginev1.UnitDomain_DOMAIN_LAND, Form: enginev1.UnitForm_FORM_DISMOUNTED_INFANTRY,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_SPECIAL_FORCES, SpecificType: "Army Special Forces ODA",
			NationOfOrigin: "USA", ServiceEntryYear: 1952,
			BaseStrength: 0.90, CombatRangeM: 800, Accuracy: 0.90,
			MaxSpeedMps: 1.5, CruiseSpeedMps: 1.1, MaxRangeKm: 60,
			Survivability: 0.65, DetectionRangeM: 1500,
			FuelCapacityLiters: 0, FuelBurnRateLph: 0,
		},
		// ── Air — Fixed Wing ────────────────────────────────────────────────────
		// Fighter/multirole aircraft are loaded from the embedded fighters library.
		{
			Id: "transport-c17-globemaster", Name: "C-17 Globemaster III", Description: "Strategic airlift transport",
			Domain: enginev1.UnitDomain_DOMAIN_AIR, Form: enginev1.UnitForm_FORM_MANNED_FIXED_WING,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_TRANSPORT_AIRCRAFT, SpecificType: "C-17A Globemaster III",
			NationOfOrigin: "USA", ServiceEntryYear: 1993,
			BaseStrength: 0.40, CombatRangeM: 0, Accuracy: 0.10,
			MaxSpeedMps: 265, CruiseSpeedMps: 232, MaxRangeKm: 10390,
			Survivability: 0.30, DetectionRangeM: 5000,
			FuelCapacityLiters: 102000, FuelBurnRateLph: 9800,
		},
		// ── Air — Unmanned ──────────────────────────────────────────────────────
		{
			Id: "isr-uav-rq4-global-hawk", Name: "RQ-4 Global Hawk", Description: "High-altitude long-endurance ISR UAV",
			Domain: enginev1.UnitDomain_DOMAIN_AIR, Form: enginev1.UnitForm_FORM_UNMANNED_FIXED_WING,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_ISR_UAV, SpecificType: "RQ-4B Global Hawk",
			NationOfOrigin: "USA", ServiceEntryYear: 1998,
			BaseStrength: 0.20, CombatRangeM: 0, Accuracy: 0.10,
			MaxSpeedMps: 175, CruiseSpeedMps: 165, MaxRangeKm: 22780,
			Survivability: 0.20, DetectionRangeM: 100000,
			FuelCapacityLiters: 7847, FuelBurnRateLph: 500,
		},
		// ── Sea — Surface ───────────────────────────────────────────────────────
		{
			Id: "carrier-nimitz-class", Name: "Nimitz Class CVN", Description: "Nuclear-powered aircraft carrier",
			Domain: enginev1.UnitDomain_DOMAIN_SEA, Form: enginev1.UnitForm_FORM_MANNED_SURFACE_SHIP,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_AIRCRAFT_CARRIER, SpecificType: "Nimitz Class",
			NationOfOrigin: "USA", ServiceEntryYear: 1975,
			BaseStrength: 1.0, CombatRangeM: 0, Accuracy: 0.90,
			MaxSpeedMps: 15.4, CruiseSpeedMps: 10.3, MaxRangeKm: 999999,
			Survivability: 0.90, DetectionRangeM: 370000,
			FuelCapacityLiters: 3000000, FuelBurnRateLph: 0,
		},
		{
			Id: "destroyer-arleigh-burke-class", Name: "Arleigh Burke Class DDG", Description: "Guided missile destroyer",
			Domain: enginev1.UnitDomain_DOMAIN_SEA, Form: enginev1.UnitForm_FORM_MANNED_SURFACE_SHIP,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_DESTROYER, SpecificType: "Arleigh Burke Class",
			NationOfOrigin: "USA", ServiceEntryYear: 1991,
			BaseStrength: 0.85, CombatRangeM: 167000, Accuracy: 0.88,
			MaxSpeedMps: 16.0, CruiseSpeedMps: 10.3, MaxRangeKm: 8100,
			Survivability: 0.70, DetectionRangeM: 370000,
			FuelCapacityLiters: 1800000, FuelBurnRateLph: 2400,
		},
		{
			Id: "frigate-constellation-class", Name: "Constellation Class FFG", Description: "Guided missile frigate",
			Domain: enginev1.UnitDomain_DOMAIN_SEA, Form: enginev1.UnitForm_FORM_MANNED_SURFACE_SHIP,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_FRIGATE, SpecificType: "Constellation Class",
			NationOfOrigin: "USA", ServiceEntryYear: 2026,
			BaseStrength: 0.75, CombatRangeM: 130000, Accuracy: 0.83,
			MaxSpeedMps: 14.4, CruiseSpeedMps: 9.3, MaxRangeKm: 7400,
			Survivability: 0.60, DetectionRangeM: 300000,
			FuelCapacityLiters: 900000, FuelBurnRateLph: 1800,
		},
		{
			Id: "corvette-generic", Name: "Corvette (Generic)", Description: "Small fast surface combatant",
			Domain: enginev1.UnitDomain_DOMAIN_SEA, Form: enginev1.UnitForm_FORM_MANNED_SURFACE_SHIP,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_CORVETTE, SpecificType: "Corvette",
			NationOfOrigin: "USA", ServiceEntryYear: 1990,
			BaseStrength: 0.55, CombatRangeM: 80000, Accuracy: 0.75,
			MaxSpeedMps: 15.4, CruiseSpeedMps: 10.3, MaxRangeKm: 4500,
			Survivability: 0.45, DetectionRangeM: 150000,
			FuelCapacityLiters: 400000, FuelBurnRateLph: 900,
		},
		{
			Id: "patrol-vessel-generic", Name: "Patrol Vessel (Generic)", Description: "Coastal patrol vessel",
			Domain: enginev1.UnitDomain_DOMAIN_SEA, Form: enginev1.UnitForm_FORM_MANNED_SURFACE_SHIP,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_PATROL_VESSEL, SpecificType: "Patrol Vessel",
			NationOfOrigin: "USA", ServiceEntryYear: 2000,
			BaseStrength: 0.35, CombatRangeM: 20000, Accuracy: 0.65,
			MaxSpeedMps: 13.9, CruiseSpeedMps: 10.3, MaxRangeKm: 2000,
			Survivability: 0.30, DetectionRangeM: 50000,
			FuelCapacityLiters: 150000, FuelBurnRateLph: 400,
		},
		// ── Sea — Subsurface ────────────────────────────────────────────────────
		{
			Id: "submarine-virginia-class", Name: "Virginia Class SSN", Description: "Fast-attack nuclear submarine",
			Domain: enginev1.UnitDomain_DOMAIN_SEA, Form: enginev1.UnitForm_FORM_MANNED_SUBMARINE,
			GeneralType: enginev1.UnitGeneralType_GENERAL_TYPE_ATTACK_SUBMARINE, SpecificType: "Virginia Class",
			NationOfOrigin: "USA", ServiceEntryYear: 2004,
			BaseStrength: 0.92, CombatRangeM: 1000000, Accuracy: 0.92,
			MaxSpeedMps: 13.4, CruiseSpeedMps: 7.7, MaxRangeKm: 999999,
			Survivability: 0.85, DetectionRangeM: 200000,
			FuelCapacityLiters: 0, FuelBurnRateLph: 0,
		},
	}
}
