package scenario

import enginev1 "github.com/aressim/internal/gen/engine/v1"

func packageProvingGroundSpecs() map[string]ProvingGroundSpec {
	return map[string]ProvingGroundSpec{
		"pg-package-iron-dome-drill": {
			ScenarioID:        "pg-package-iron-dome-drill",
			Category:          "package",
			Purpose:           "Validate the reusable Iron Dome package in isolation against a small missile raid.",
			ExpectedSummary:   "The Iron Dome package should intercept some inbound projectiles, but a small amount of leakage should remain possible.",
			RecommendedTrials: 10,
			MaxSimSeconds:     1800,
			FocusTeam:         "ISR",
			OpposingTeam:      "IRN",
			SetupActions: []ProvingGroundSetupAction{
				{Kind: "set_player", TeamID: "ISR"},
				{Kind: "assign_attack", UnitID: "pg-pkg-id-irn-kheibar-1", TargetUnitID: "pg-pkg-id-ashdod-port", OrderType: enginev1.AttackOrderType_ATTACK_ORDER_TYPE_STRIKE_UNTIL_EFFECT, DesiredEffect: enginev1.DesiredEffect_DESIRED_EFFECT_MISSION_KILL},
				{Kind: "assign_attack", UnitID: "pg-pkg-id-irn-kheibar-2", TargetUnitID: "pg-pkg-id-ashdod-port", OrderType: enginev1.AttackOrderType_ATTACK_ORDER_TYPE_STRIKE_UNTIL_EFFECT, DesiredEffect: enginev1.DesiredEffect_DESIRED_EFFECT_MISSION_KILL},
			},
			MinInterceptionRate:   0.40,
			MaxMeanFocusHitsTaken: 4,
		},
		"pg-package-al-udeid-sortie": {
			ScenarioID:          "pg-package-al-udeid-sortie",
			Category:            "package",
			Purpose:             "Validate the reusable Al Udeid package for hosted launch, strike, return, reserve aircraft, and replenishment behavior.",
			ExpectedSummary:     "The hosted strike element should launch from Al Udeid, hit Bushehr in a meaningful share of runs, and at least one aircraft should recover and enter replenishment while a second target remains available.",
			RecommendedTrials:   10,
			MaxSimSeconds:       5400,
			FocusTeam:           "USA",
			OpposingTeam:        "IRN",
			TrackedTargetUnitID: "pg-pkg-au-bushehr",
			SetupActions: []ProvingGroundSetupAction{
				{Kind: "set_player", TeamID: "USA"},
				{Kind: "preview_target", TeamID: "USA", TargetUnitID: "pg-pkg-au-bushehr", ExpectedShooterUnitID: "pg-pkg-au-f15e-lead"},
				{Kind: "assign_attack", UnitID: "pg-pkg-au-f15e-lead", TargetUnitID: "pg-pkg-au-bushehr", OrderType: enginev1.AttackOrderType_ATTACK_ORDER_TYPE_STRIKE_UNTIL_EFFECT, DesiredEffect: enginev1.DesiredEffect_DESIRED_EFFECT_MISSION_KILL},
			},
			MinTargetMissionKillRate: 0.40,
		},
		"pg-package-layered-israel-defense": {
			ScenarioID:            "pg-package-layered-israel-defense",
			Category:              "package",
			Purpose:               "Validate package composition by combining reusable layered Israeli defense, Iranian launcher, and strike packages in one live scenario.",
			ExpectedSummary:       "The layered package should intercept many inbound missiles while the counterstrike package destroys some launchers and some leakage still gets through.",
			RecommendedTrials:     10,
			MaxSimSeconds:         3600,
			FocusTeam:             "ISR",
			OpposingTeam:          "IRN",
			MinInterceptionRate:   0.60,
			MinMeanOpposingLosses: 0.50,
			MaxMeanFocusHitsTaken: 8,
		},
		"pg-package-bahrain-maritime-presence": {
			ScenarioID:                "pg-package-bahrain-maritime-presence",
			Category:                  "package",
			Purpose:                   "Validate the reusable Bahrain naval support package in a small Gulf littoral-defense scenario.",
			ExpectedSummary:           "The Bahrain package should present a plausible mixed Bahraini/U.S. local naval presence and defeat a small Iranian surface raider in most runs.",
			RecommendedTrials:         10,
			MaxSimSeconds:             1800,
			FocusTeam:                 "COALITION_WEST",
			OpposingTeam:              "IRN",
			TrackedTargetUnitID:       "pg-pkg-bh-irn-raider",
			EndOnTrackedTargetDisable: true,
			MinFocusWinRate:           0.70,
			MinTargetMissionKillRate:  0.70,
		},
		"pg-package-al-dhafra-forward-strike": {
			ScenarioID:          "pg-package-al-dhafra-forward-strike",
			Category:            "package",
			Purpose:             "Validate the reusable Al Dhafra package as a Gulf forward-strike and support package with sovereign/operator split preserved.",
			ExpectedSummary:     "The Al Dhafra package should launch hosted F-35s and mission-kill Bandar Abbas in a meaningful share of runs.",
			RecommendedTrials:   10,
			MaxSimSeconds:       3600,
			FocusTeam:           "USA",
			OpposingTeam:        "IRN",
			TrackedTargetUnitID: "pg-pkg-ad-bandar-abbas",
			SetupActions: []ProvingGroundSetupAction{
				{Kind: "set_player", TeamID: "USA"},
				{Kind: "preview_target", TeamID: "USA", TargetUnitID: "pg-pkg-ad-bandar-abbas", ExpectedShooterUnitID: "pg-pkg-ad-f35a-lead"},
				{Kind: "assign_attack", UnitID: "pg-pkg-ad-f35a-lead", TargetUnitID: "pg-pkg-ad-bandar-abbas", OrderType: enginev1.AttackOrderType_ATTACK_ORDER_TYPE_STRIKE_UNTIL_EFFECT, DesiredEffect: enginev1.DesiredEffect_DESIRED_EFFECT_MISSION_KILL},
			},
			MinFocusWinRate:          0.70,
			MinTargetMissionKillRate: 0.40,
		},
		"pg-package-gulf-regional-support-posture": {
			ScenarioID:          "pg-package-gulf-regional-support-posture",
			Category:            "package",
			Purpose:             "Validate interoperability of reusable Gulf packages by combining Al Udeid, Al Dhafra, and Bahrain against Iranian air and littoral threats.",
			ExpectedSummary:     "The composed Gulf posture should defend against at least one Iranian air and maritime threat while still generating a meaningful strike against Bushehr.",
			RecommendedTrials:   10,
			MaxSimSeconds:       3600,
			FocusTeam:           "USA",
			OpposingTeam:        "IRN",
			TrackedTargetUnitID: "pg-pkg-grs-bushehr",
			SetupActions: []ProvingGroundSetupAction{
				{Kind: "set_player", TeamID: "USA"},
				{Kind: "preview_target", TeamID: "USA", TargetUnitID: "pg-pkg-grs-bushehr", ExpectedShooterUnitID: "pg-pkg-grs-au-f15e-lead"},
				{Kind: "assign_attack", UnitID: "pg-pkg-grs-au-f15e-lead", TargetUnitID: "pg-pkg-grs-bushehr", OrderType: enginev1.AttackOrderType_ATTACK_ORDER_TYPE_STRIKE_UNTIL_EFFECT, DesiredEffect: enginev1.DesiredEffect_DESIRED_EFFECT_MISSION_KILL},
				{Kind: "preview_target", TeamID: "USA", TargetUnitID: "pg-pkg-grs-bandar-abbas", ExpectedShooterUnitID: "pg-pkg-grs-ad-f35a-lead"},
				{Kind: "assign_attack", UnitID: "pg-pkg-grs-ad-f35a-lead", TargetUnitID: "pg-pkg-grs-bandar-abbas", OrderType: enginev1.AttackOrderType_ATTACK_ORDER_TYPE_STRIKE_UNTIL_EFFECT, DesiredEffect: enginev1.DesiredEffect_DESIRED_EFFECT_MISSION_KILL},
			},
			MinFocusWinRate:          0.40,
			MinTargetMissionKillRate: 0.40,
			MinMeanOpposingLosses:    1.00,
		},
		"pg-package-hormuz-coastal-denial": {
			ScenarioID:                "pg-package-hormuz-coastal-denial",
			Category:                  "package",
			Purpose:                   "Validate the reusable Iranian Hormuz coastal-denial package against a mixed western Gulf transit group.",
			ExpectedSummary:           "The coastal-denial package should produce meaningful mission effects on at least one transit combatant while still taking some attrition from the defending group.",
			RecommendedTrials:         10,
			MaxSimSeconds:             2400,
			FocusTeam:                 "IRN",
			OpposingTeam:              "USA",
			TrackedTargetUnitID:       "pg-pkg-hcd-lcs",
			EndOnTrackedTargetDisable: true,
			MinFocusWinRate:           0.40,
			MinTargetMissionKillRate:  0.40,
			MinMeanOpposingLosses:     0.40,
		},
		"pg-package-uae-coastal-defense": {
			ScenarioID:                "pg-package-uae-coastal-defense",
			Category:                  "package",
			Purpose:                   "Validate the reusable Emirati coastal-defense package against the Iranian Hormuz coastal-denial package.",
			ExpectedSummary:           "The Emirati package should impose some attrition on the Iranian littoral package, but the exchange should still be dangerous and contested.",
			RecommendedTrials:         10,
			MaxSimSeconds:             2400,
			FocusTeam:                 "ARE",
			OpposingTeam:              "IRN",
			TrackedTargetUnitID:       "pg-pkg-uacd-irn-soleimani",
			EndOnTrackedTargetDisable: true,
			MinFocusWinRate:           0.20,
			MinTargetMissionKillRate:  0.20,
			MinMeanOpposingLosses:     0.20,
		},
		"pg-package-oman-musandam-strait-guard": {
			ScenarioID:                "pg-package-oman-musandam-strait-guard",
			Category:                  "package",
			Purpose:                   "Validate the reusable Omani Musandam package against the Iranian Hormuz coastal-denial package on the southern side of the strait.",
			ExpectedSummary:           "The Omani package should contest the Iranian littoral package, inflict some losses, and keep the exchange dangerous rather than one-sided.",
			RecommendedTrials:         10,
			MaxSimSeconds:             2400,
			FocusTeam:                 "OMN",
			OpposingTeam:              "IRN",
			TrackedTargetUnitID:       "pg-pkg-omsg-irn-soleimani",
			EndOnTrackedTargetDisable: true,
			MinFocusWinRate:           0.20,
			MinTargetMissionKillRate:  0.20,
			MinMeanOpposingLosses:     0.20,
		},
		"pg-package-strait-regional-control": {
			ScenarioID:                "pg-package-strait-regional-control",
			Category:                  "package",
			Purpose:                   "Validate interoperability of reusable UAE, Oman, and Bahrain Gulf packages against the Iranian Hormuz coastal-denial package.",
			ExpectedSummary:           "The western and southern Strait packages should collectively inflict losses on the Iranian denial package and usually neutralize at least one major threat unit, but the exchange should remain dangerous and contested.",
			RecommendedTrials:         10,
			MaxSimSeconds:             3000,
			FocusTeam:                 "COALITION_WEST",
			OpposingTeam:              "IRN",
			TrackedTargetUnitID:       "pg-pkg-src-irn-soleimani",
			EndOnTrackedTargetDisable: true,
			MinFocusWinRate:           0.30,
			MinTargetMissionKillRate:  0.30,
			MinMeanOpposingLosses:     0.50,
		},
	}
}

func packageProvingGroundBuiltins() []*enginev1.Scenario {
	return []*enginev1.Scenario{
		provingGroundPackageIronDomeDrill(),
		provingGroundPackageAlUdeidSortie(),
		provingGroundPackageLayeredIsraelDefense(),
		provingGroundPackageBahrainMaritimePresence(),
		provingGroundPackageAlDhafraForwardStrike(),
		provingGroundPackageGulfRegionalSupportPosture(),
		provingGroundPackageHormuzCoastalDenial(),
		provingGroundPackageUAECoastalDefense(),
		provingGroundPackageOMNMusandamStraitGuard(),
		provingGroundPackageStraitRegionalControl(),
	}
}
