/**
 * simStore.ts
 *
 * Central Zustand store for simulation state. This is the single source of
 * truth for the frontend. The store is updated by the event bridge (bridge.ts)
 * and read by React components and the CesiumJS renderer.
 *
 * Design principle: CesiumJS does NOT subscribe to this store via React hooks.
 * Instead, the CesiumJS renderer calls store.subscribe() to get raw state
 * diffs and updates entities imperatively. This avoids triggering a React
 * re-render on every tick (which would be 10x/sec with 1000+ units).
 *
 * React components (HUD, event log, unit panel) use useSimStore() normally —
 * they only re-render when their specific slice changes.
 */

import { create } from "zustand";

// ─── TYPES ────────────────────────────────────────────────────────────────────
// These mirror the proto message shapes after JSON deserialization.
// The full proto types (from @proto/engine/v1/*_pb.ts) are used in bridge.ts
// for deserialization; the store uses plain objects for simpler rendering.

export interface Position {
  lat: number;
  lon: number;
  altMsl: number;
  heading: number;
  speed: number;
}

export interface Waypoint {
  lat: number;
  lon: number;
  altMsl: number;
}

export interface MoveOrder {
  waypoints: Waypoint[];
  autoGenerated?: boolean;
}

export interface UnitStatus {
  personnelStrength: number;
  equipmentStrength: number;
  combatEffectiveness: number;
  fuelLevelLiters: number;
  morale: number;
  fatigue: number;
  isActive: boolean;
  suppressed: boolean;
  disrupted: boolean;
  routing: boolean;
}

export interface WeaponState {
  weaponId: string;
  currentQty: number;
  maxQty: number;
}

export interface Munition {
  id: string;
  weaponId: string;
  shooterId: string;
  lat: number;
  lon: number;
  altMsl: number;
}

export interface ExplosionFx {
  id: string;
  lat: number;
  lon: number;
  altMsl: number;
  kind: "impact" | "kill";
}

export interface WeaponDef {
  id: string;
  name: string;
  description: string;
  domainTargets: number[];  // UnitDomain enum values
  speedMps: number;
  rangeM: number;
  probabilityOfHit: number;
  effectType: number;
}

export interface DetectionContact {
  unitId: string;
  sourceTeam: string;
  shared: boolean;
}

export interface CountryRelationship {
  fromCountry: string;
  toCountry: string;
  shareIntel: boolean;
  airspaceTransitAllowed: boolean;
  airspaceStrikeAllowed: boolean;
  defensivePositioningAllowed: boolean;
  maritimeTransitAllowed: boolean;
  maritimeStrikeAllowed: boolean;
}

export interface TeamScore {
  teamId: string;
  replacementLossUsd: number;
  strategicLossUsd: number;
  economicLossUsd: number;
  humanLossUsd: number;
  totalLossUsd: number;
}

export interface MapCommandMode {
  type: "none" | "route" | "target_pick";
  unitId: string | null;
}

export interface PathViolationPreview {
  blocked: boolean;
  country?: string;
  legIndex?: number;
  reason?: string;
}

export interface Unit {
  id: string;
  displayName: string;
  fullName: string;
  side: string;  // "Blue" | "Red" | "Neutral"
  teamId?: string;
  coalitionId?: string;
  natoPendingSymbol: string;  // NATO APP-6D SIDC code
  definitionId: string;
  hostBaseId?: string;
  loadoutConfigurationId?: string;
  damageState: number;
  nextSortieReadySeconds?: number;
  nextStrikeReadySeconds?: number;
  baseOps?: {
    state: number;
    nextLaunchAvailableSeconds: number;
    nextRecoveryAvailableSeconds: number;
  };
  engagementBehavior?: number;
  engagementPkillThreshold?: number;
  attackOrder?: {
    orderType: number;
    targetUnitId: string;
    desiredEffect: number;
    pkillThreshold: number;
  };
  position: Position;
  status: UnitStatus;
  parentUnitId?: string;
  moveOrder?: MoveOrder;
  weapons: WeaponState[];
}

export type ScenarioState = "idle" | "paused" | "running" | "ended";

export interface SimStore {
  // ── Scenario ────────────────────────────────────────────────────────────
  scenarioName: string;
  scenarioState: ScenarioState;
  timeScale: number;
  simSeconds: number;
  tickNumber: number;
  relationships: CountryRelationship[];
  scores: TeamScore[];

  // ── Units ────────────────────────────────────────────────────────────────
  // Map keyed by unit ID for O(1) lookup and incremental delta merges.
  units: Map<string, Unit>;

  // ── Weapon definitions ────────────────────────────────────────────────────
  // Global munition catalog keyed by weapon ID. Populated from full_state_snapshot.
  weaponDefs: Map<string, WeaponDef>;

  // ── In-flight munitions ───────────────────────────────────────────────────
  // Keyed by munition ID. Replaced in full each tick via munition_update.
  munitions: Map<string, Munition>;

  // ── Transient effects ─────────────────────────────────────────────────────
  // Short-lived render-only FX such as missile impacts and kill explosions.
  explosions: Map<string, ExplosionFx>;

  // ── Munition detections ───────────────────────────────────────────────────
  // Maps detecting side → set of munition IDs currently visible to that side.
  munitionDetections: Map<string, Set<string>>;

  // ── View ─────────────────────────────────────────────────────────────────
  // Controls fog of war: "debug" shows all units; any other value is a
  // team/nation code such as "ISR" or "USA".
  activeView: string;
  humanControlledTeam: string;

  // ── Detections ───────────────────────────────────────────────────────────
  // Maps detecting side → set of enemy unit IDs currently in sensor range.
  // Updated every tick by the adjudicator's sensor pass. Replaced in full
  // (not merged) so stale contacts are automatically cleared.
  detections: Map<string, Set<string>>;
  detectionContacts: Map<string, Map<string, DetectionContact>>;

  // ── Selection ────────────────────────────────────────────────────────────
  selectedUnitId: string | null;
  mapCommandMode: MapCommandMode;
  selectedRoutePreview: PathViolationPreview | null;
  selectedStrikePreview: PathViolationPreview | null;

  // ── Event log ────────────────────────────────────────────────────────────
  // Capped at 200 entries; oldest dropped when full.
  eventLog: EventLogEntry[];

  // ── Actions ──────────────────────────────────────────────────────────────
  // Called by bridge.ts on incoming sim events.
  loadSnapshot: (units: Unit[], scenarioName: string, weaponDefs?: WeaponDef[], relationships?: CountryRelationship[], scores?: TeamScore[]) => void;
  setRelationships: (relationships: CountryRelationship[]) => void;
  setScores: (scores: TeamScore[]) => void;
  setMunitions: (munitions: Munition[]) => void;
  addExplosion: (explosion: ExplosionFx) => void;
  removeExplosion: (id: string) => void;
  setMunitionDetections: (side: string, ids: string[]) => void;
  applyUnitDelta: (id: string, delta: Partial<Unit>) => void;
  spawnUnit: (unit: Unit) => void;
  destroyUnit: (id: string) => void;
  setScenarioState: (state: ScenarioState, timeScale: number) => void;
  setSimTime: (seconds: number, tick: number) => void;
  appendEventLog: (entry: EventLogEntry) => void;
  selectUnit: (id: string | null) => void;
  startRouteEdit: (id: string | null) => void;
  startTargetPick: (id: string | null) => void;
  clearMapCommandMode: () => void;
  setSelectedRoutePreview: (preview: PathViolationPreview | null) => void;
  setSelectedStrikePreview: (preview: PathViolationPreview | null) => void;
  setActiveView: (view: string) => void;
  setHumanControlledTeam: (team: string) => void;
  setDetections: (side: string, ids: string[], contacts?: DetectionContact[]) => void;
}

export interface EventLogEntry {
  id: string;        // UUID from NarrativeEvent
  text: string;
  category: string;  // "combat" | "logistics" | "c2" | "intelligence" | "scenario"
  unitId: string;
  side: string;
  simSeconds: number;
}

const MAX_EVENT_LOG = 200;

export const useSimStore = create<SimStore>((set) => ({
  scenarioName: "",
  scenarioState: "idle",
  timeScale: 1.0,
  simSeconds: 0,
  tickNumber: 0,
  relationships: [],
  scores: [],
  units: new Map(),
  weaponDefs: new Map(),
  munitions: new Map(),
  explosions: new Map(),
  munitionDetections: new Map(),
  activeView: "debug",
  humanControlledTeam: "",
  detections: new Map(),
  detectionContacts: new Map(),
  selectedUnitId: null,
  mapCommandMode: { type: "none", unitId: null },
  selectedRoutePreview: null,
  selectedStrikePreview: null,
  eventLog: [],

  loadSnapshot: (units, scenarioName, weaponDefs, relationships, scores) =>
    // Replaces the entire units Map reference. Zustand notifies all subscribers
    // because the reference changed, so CesiumGlobe's subscription fires and
    // does a full syncUnits pass. This is correct: a snapshot is a full rebuild.
    set((state) => ({
      scenarioName,
      scenarioState: "paused",
      simSeconds: 0,
      tickNumber: 0,
      relationships: relationships ?? state.relationships,
      scores: scores ?? state.scores,
      units: new Map(units.map((u) => [u.id, u])),
      selectedUnitId: null,
      mapCommandMode: { type: "none", unitId: null },
      selectedRoutePreview: null,
      selectedStrikePreview: null,
      munitions: new Map(),
      explosions: new Map(),
      detections: new Map(),
      detectionContacts: new Map(),
      eventLog: [],
      weaponDefs: weaponDefs
        ? new Map(weaponDefs.map((d) => [d.id, d]))
        : state.weaponDefs,
      humanControlledTeam: state.scenarioName === scenarioName ? state.humanControlledTeam : "",
    })),

  applyUnitDelta: (id, delta) =>
    set((state) => {
      const existing = state.units.get(id);
      if (!existing) return {};
      const updated = new Map(state.units);
      const merged = { ...existing, ...delta };
      // When a weapons delta arrives, merge by weaponId rather than replacing
      // the entire array, so un-fired weapons retain their previous quantities.
      if (delta.weapons && delta.weapons.length > 0) {
        const weaponMap = new Map(existing.weapons.map((w) => [w.weaponId, w]));
        for (const w of delta.weapons) {
          weaponMap.set(w.weaponId, w);
        }
        merged.weapons = Array.from(weaponMap.values());
      }
      updated.set(id, merged);
      return { units: updated };
    }),

  spawnUnit: (unit) =>
    set((state) => {
      const updated = new Map(state.units);
      updated.set(unit.id, unit);
      return { units: updated };
    }),

  destroyUnit: (id) =>
    set((state) => {
      const updated = new Map(state.units);
      const unit = updated.get(id);
      if (unit) {
        updated.set(id, { ...unit, damageState: 4, status: { ...unit.status, isActive: false } });
      }
      return { units: updated };
    }),

  setScenarioState: (scenarioState, timeScale) =>
    set({ scenarioState, timeScale }),

  setSimTime: (simSeconds, tickNumber) =>
    set({ simSeconds, tickNumber }),

  setRelationships: (relationships) => set({ relationships }),
  setScores: (scores) => set({ scores }),

  appendEventLog: (entry) =>
    set((state) => {
      const log = [...state.eventLog, entry];
      return { eventLog: log.length > MAX_EVENT_LOG ? log.slice(-MAX_EVENT_LOG) : log };
    }),

  selectUnit: (selectedUnitId) => set({ selectedUnitId }),
  startRouteEdit: (unitId) => set({ mapCommandMode: unitId ? { type: "route", unitId } : { type: "none", unitId: null } }),
  startTargetPick: (unitId) => set({ mapCommandMode: unitId ? { type: "target_pick", unitId } : { type: "none", unitId: null } }),
  clearMapCommandMode: () => set({ mapCommandMode: { type: "none", unitId: null } }),
  setSelectedRoutePreview: (selectedRoutePreview) => set({ selectedRoutePreview }),
  setSelectedStrikePreview: (selectedStrikePreview) => set({ selectedStrikePreview }),
  setActiveView: (activeView) => set({ activeView }),
  setHumanControlledTeam: (humanControlledTeam) => set({ humanControlledTeam }),

  setDetections: (side, ids, contacts = []) =>
    set((state) => {
      const updated = new Map(state.detections);
      updated.set(side, new Set(ids));
      const updatedContacts = new Map(state.detectionContacts);
      updatedContacts.set(side, new Map(contacts.map((contact) => [contact.unitId, contact])));
      return { detections: updated, detectionContacts: updatedContacts };
    }),

  setMunitions: (munitions) =>
    set({ munitions: new Map(munitions.map((m) => [m.id, m])) }),

  addExplosion: (explosion) =>
    set((state) => {
      const updated = new Map(state.explosions);
      updated.set(explosion.id, explosion);
      return { explosions: updated };
    }),

  removeExplosion: (id) =>
    set((state) => {
      if (!state.explosions.has(id)) return {};
      const updated = new Map(state.explosions);
      updated.delete(id);
      return { explosions: updated };
    }),

  setMunitionDetections: (side, ids) =>
    set((state) => {
      const updated = new Map(state.munitionDetections);
      updated.set(side, new Set(ids));
      return { munitionDetections: updated };
    }),
}));
