export interface Position {
  lat: number;
  lon: number;
  altMsl: number;
  heading: number;
  speed: number;
  h3Cell?: string;
  h3ParentCell?: string;
}

export interface Waypoint {
  lat: number;
  lon: number;
  altMsl: number;
  h3Cell?: string;
  h3ParentCell?: string;
}

export interface MoveOrder {
  waypoints: Waypoint[];
  autoGenerated?: boolean;
}

export interface UnitStatus {
  personnelStrength: number;
  equipmentStrength: number;
  combatEffectiveness: number;
  fuelLevelLiters: number;
  morale: number;
  fatigue: number;
  isActive: boolean;
  suppressed: boolean;
  disrupted: boolean;
  routing: boolean;
}

export interface WeaponState {
  weaponId: string;
  currentQty: number;
  maxQty: number;
}

export interface Munition {
  id: string;
  weaponId: string;
  shooterId: string;
  lat: number;
  lon: number;
  altMsl: number;
}

export interface ExplosionFx {
  id: string;
  lat: number;
  lon: number;
  altMsl: number;
  kind: "impact" | "kill";
}

export interface WeaponDef {
  id: string;
  name: string;
  description: string;
  domainTargets: number[];
  speedMps: number;
  rangeM: number;
  probabilityOfHit: number;
  effectType: number;
}

export interface DetectionContact {
  unitId: string;
  sourceTeam: string;
  shared: boolean;
}

export interface CountryRelationship {
  fromCountry: string;
  toCountry: string;
  shareIntel: boolean;
  airspaceTransitAllowed: boolean;
  airspaceStrikeAllowed: boolean;
  defensivePositioningAllowed: boolean;
  maritimeTransitAllowed: boolean;
  maritimeStrikeAllowed: boolean;
}

export interface TeamScore {
  teamId: string;
  replacementLossUsd: number;
  strategicLossUsd: number;
  economicLossUsd: number;
  humanLossUsd: number;
  totalLossUsd: number;
}

export interface MapCommandMode {
  type: "none" | "route";
  unitId: string | null;
}

export interface PathViolationPreview {
  blocked: boolean;
  country?: string;
  legIndex?: number;
  reason?: string;
  routePoints?: { lat: number; lon: number; h3Cell?: string; h3ParentCell?: string }[];
}

export interface OilSourceRef {
  name: string;
  organization: string;
  url: string;
  lastUpdated?: string;
  confidence: number;
  notes?: string;
}

export interface OilCommodityQuantity {
  commodity: string;
  bpd?: number;
  barrels?: number;
}

export interface OilProductOutput {
  commodity: string;
  bpd: number;
}

export interface OilRoutePoint {
  lat: number;
  lon: number;
}

export interface OilNode {
  id: string;
  name: string;
  kind: string;
  countryCode: string;
  operator?: string;
  lat: number;
  lon: number;
  h3Cell?: string;
  h3ParentCell?: string;
  state: string;
  primaryCommodity?: string;
  parentProjectId?: string;
  childFieldIds?: string[];
  capacityBpd?: number;
  currentFlowBpd?: number;
  spareCapacityBpd?: number;
  productionBpd?: number;
  reserveBbl?: number;
  crudeIntakeBpd?: number;
  productOutputs?: OilProductOutput[];
  outlineRings?: OilRoutePoint[][];
  demandProfile?: OilCommodityQuantity[];
  inventory?: OilCommodityQuantity[];
  dailyDrawLimitBpd?: number;
  storageCapacityBbl?: number;
  tags?: string[];
  sources?: OilSourceRef[];
}

export interface OilEdge {
  id: string;
  name: string;
  kind: string;
  fromNodeId: string;
  toNodeId: string;
  commodity: string;
  commodities?: string[];
  commodityLabel?: string;
  state: string;
  capacityBpd: number;
  currentFlowBpd: number;
  transitDays?: number;
  lengthKm?: number;
  reversible?: boolean;
  crossesChokepoint?: string;
  crossesChokepoints?: string[];
  route?: OilRoutePoint[];
  routes?: OilRoutePoint[][];
  sources?: OilSourceRef[];
}

export interface OilGraph {
  id: string;
  name: string;
  description: string;
  version: string;
  view: string;
  nodes: OilNode[];
  edges: OilEdge[];
  sources?: OilSourceRef[];
}

export interface Unit {
  id: string;
  displayName: string;
  fullName: string;
  teamId?: string;
  coalitionId?: string;
  operatorTeamId?: string;
  natoPendingSymbol: string;
  definitionId: string;
  hostBaseId?: string;
  loadoutConfigurationId?: string;
  damageState: number;
  nextSortieReadySeconds?: number;
  nextStrikeReadySeconds?: number;
  baseOps?: {
    state: number;
    nextLaunchAvailableSeconds: number;
    nextRecoveryAvailableSeconds: number;
  };
  engagementBehavior?: number;
  engagementPkillThreshold?: number;
  attackOrder?: {
    orderType: number;
    targetUnitId: string;
    desiredEffect: number;
    pkillThreshold: number;
  };
  position: Position;
  status: UnitStatus;
  parentUnitId?: string;
  moveOrder?: MoveOrder;
  weapons: WeaponState[];
}

export type ScenarioState = "idle" | "paused" | "running" | "ended";

export interface EventLogEntry {
  id: string;
  text: string;
  category: string;
  unitId: string;
  teamId: string;
  simSeconds: number;
}

export interface SimStore {
  scenarioName: string;
  scenarioState: ScenarioState;
  timeScale: number;
  simSeconds: number;
  tickNumber: number;
  relationships: CountryRelationship[];
  scores: TeamScore[];
  units: Map<string, Unit>;
  weaponDefs: Map<string, WeaponDef>;
  munitions: Map<string, Munition>;
  explosions: Map<string, ExplosionFx>;
  munitionDetections: Map<string, Set<string>>;
  activeView: string;
  humanControlledTeam: string;
  oilGraph: OilGraph | null;
  oilLayerVisible: boolean;
  oilFocusToken: number;
  oilLoadError: string | null;
  detections: Map<string, Set<string>>;
  detectionContacts: Map<string, Map<string, DetectionContact>>;
  selectedUnitId: string | null;
  selectedTargetId: string | null;
  selectedOilNodeId: string | null;
  selectedOilEdgeId: string | null;
  mapCommandMode: MapCommandMode;
  selectedRoutePreview: PathViolationPreview | null;
  selectedStrikePreview: PathViolationPreview | null;
  eventLog: EventLogEntry[];
  loadSnapshot: (units: Unit[], scenarioName: string, weaponDefs?: WeaponDef[], relationships?: CountryRelationship[], scores?: TeamScore[]) => void;
  setRelationships: (relationships: CountryRelationship[]) => void;
  setScores: (scores: TeamScore[]) => void;
  setMunitions: (munitions: Munition[]) => void;
  addExplosion: (explosion: ExplosionFx) => void;
  removeExplosion: (id: string) => void;
  setMunitionDetections: (teamId: string, ids: string[]) => void;
  applyUnitDelta: (id: string, delta: Partial<Unit>) => void;
  spawnUnit: (unit: Unit) => void;
  destroyUnit: (id: string) => void;
  setScenarioState: (state: ScenarioState, timeScale: number) => void;
  setSimTime: (seconds: number, tick: number) => void;
  appendEventLog: (entry: EventLogEntry) => void;
  selectUnit: (id: string | null) => void;
  selectTarget: (id: string | null) => void;
  startRouteEdit: (id: string | null) => void;
  clearMapCommandMode: () => void;
  setSelectedRoutePreview: (preview: PathViolationPreview | null) => void;
  setSelectedStrikePreview: (preview: PathViolationPreview | null) => void;
  setActiveView: (view: string) => void;
  setHumanControlledTeam: (team: string) => void;
  setDetections: (teamId: string, ids: string[], contacts?: DetectionContact[]) => void;
  setOilGraph: (graph: OilGraph | null) => void;
  setOilLoadError: (message: string | null) => void;
  setOilLayerVisible: (visible: boolean) => void;
  requestOilFocus: () => void;
  selectOilNode: (id: string | null) => void;
  selectOilEdge: (id: string | null) => void;
}
