// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/common.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/common.proto.
 */
export const file_engine_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvY29tbW9uLnByb3RvEgllbmdpbmUudjEifgoIUG9zaXRpb24SCwoDbGF0GAEgASgBEgsKA2xvbhgCIAEoARIPCgdhbHRfbXNsGAMgASgBEg8KB2hlYWRpbmcYBCABKAESDQoFc3BlZWQYBSABKAESDwoHaDNfY2VsbBgGIAEoCRIWCg5oM19wYXJlbnRfY2VsbBgHIAEoCSI3CgdTaW1UaW1lEhcKD3NlY29uZHNfZWxhcHNlZBgBIAEoARITCgt0aWNrX251bWJlchgCIAEoAyKxAQoRV2VhdGhlckNvbmRpdGlvbnMSJgoFc3RhdGUYASABKA4yFy5lbmdpbmUudjEuV2VhdGhlclN0YXRlEhUKDXZpc2liaWxpdHlfa20YAiABKAISFgoOd2luZF9zcGVlZF9tcHMYAyABKAISFQoNcHJlY2lwaXRhdGlvbhgEIAEoCBIVCg10ZW1wZXJhdHVyZV9jGAUgASgCEhcKD2Nsb3VkX2NlaWxpbmdfbRgGIAEoAiIxCg9PcGVyYXRpb25SZXN1bHQSDwoHc3VjY2VzcxgBIAEoCBINCgVlcnJvchgCIAEoCSJeCghXYXlwb2ludBILCgNsYXQYASABKAESCwoDbG9uGAIgASgBEg8KB2FsdF9tc2wYAyABKAESDwoHaDNfY2VsbBgEIAEoCRIWCg5oM19wYXJlbnRfY2VsbBgFIAEoCSJLCglNb3ZlT3JkZXISJgoJd2F5cG9pbnRzGAEgAygLMhMuZW5naW5lLnYxLldheXBvaW50EhYKDmF1dG9fZ2VuZXJhdGVkGAIgASgIKrMBCgxXZWF0aGVyU3RhdGUSFwoTV0VBVEhFUl9VTlNQRUNJRklFRBAAEhEKDVdFQVRIRVJfQ0xFQVIQARIUChBXRUFUSEVSX09WRVJDQVNUEAISDwoLV0VBVEhFUl9GT0cQAxIQCgxXRUFUSEVSX1JBSU4QBBIWChJXRUFUSEVSX0hFQVZZX1JBSU4QBRIQCgxXRUFUSEVSX1NOT1cQBhIUChBXRUFUSEVSX0JMSVpaQVJEEAcqbAoKVW5pdERvbWFpbhIWChJET01BSU5fVU5TUEVDSUZJRUQQABIPCgtET01BSU5fTEFORBABEg4KCkRPTUFJTl9BSVIQAhIOCgpET01BSU5fU0VBEAMSFQoRRE9NQUlOX1NVQlNVUkZBQ0UQBCrLAQoQRm9ybWF0aW9uUG9zdHVyZRIXChNQT1NUVVJFX1VOU1BFQ0lGSUVEEAASFQoRUE9TVFVSRV9UUkFWRUxJTkcQARIUChBQT1NUVVJFX0JPVU5ESU5HEAISFgoSUE9TVFVSRV9ERUxJQkVSQVRFEAMSGQoVUE9TVFVSRV9IQVNUWV9ERUZFTlNFEAQSEgoOUE9TVFVSRV9EVUdfSU4QBRIVChFQT1NUVVJFX0RJU1BFUlNFRBAGEhMKD1BPU1RVUkVfQVNTQVVMVBAHQitaKWdpdGh1Yi5jb20vYXJlc3NpbS9pbnRlcm5hbC9nZW4vZW5naW5lL3YxYgZwcm90bzM");

/**
 * @generated from message engine.v1.Position
 */
export type Position = Message<"engine.v1.Position"> & {
  /**
   * Decimal degrees -90..+90
   *
   * @generated from field: double lat = 1;
   */
  lat: number;

  /**
   * Decimal degrees -180..+180
   *
   * @generated from field: double lon = 2;
   */
  lon: number;

  /**
   * Meters above mean sea level
   *
   * @generated from field: double alt_msl = 3;
   */
  altMsl: number;

  /**
   * True north bearing 0–360°
   *
   * @generated from field: double heading = 4;
   */
  heading: number;

  /**
   * Meters per second
   *
   * @generated from field: double speed = 5;
   */
  speed: number;

  /**
   * Canonical H3 cell at repo default precision (r12)
   *
   * @generated from field: string h3_cell = 6;
   */
  h3Cell: string;

  /**
   * Aggregation parent H3 cell (typically r11)
   *
   * @generated from field: string h3_parent_cell = 7;
   */
  h3ParentCell: string;
};

/**
 * Describes the message engine.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 0);

/**
 * @generated from message engine.v1.SimTime
 */
export type SimTime = Message<"engine.v1.SimTime"> & {
  /**
   * @generated from field: double seconds_elapsed = 1;
   */
  secondsElapsed: number;

  /**
   * @generated from field: int64 tick_number = 2;
   */
  tickNumber: bigint;
};

/**
 * Describes the message engine.v1.SimTime.
 * Use `create(SimTimeSchema)` to create a new message.
 */
export const SimTimeSchema: GenMessage<SimTime> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 1);

/**
 * @generated from message engine.v1.WeatherConditions
 */
export type WeatherConditions = Message<"engine.v1.WeatherConditions"> & {
  /**
   * @generated from field: engine.v1.WeatherState state = 1;
   */
  state: WeatherState;

  /**
   * @generated from field: float visibility_km = 2;
   */
  visibilityKm: number;

  /**
   * @generated from field: float wind_speed_mps = 3;
   */
  windSpeedMps: number;

  /**
   * @generated from field: bool precipitation = 4;
   */
  precipitation: boolean;

  /**
   * @generated from field: float temperature_c = 5;
   */
  temperatureC: number;

  /**
   * @generated from field: float cloud_ceiling_m = 6;
   */
  cloudCeilingM: number;
};

/**
 * Describes the message engine.v1.WeatherConditions.
 * Use `create(WeatherConditionsSchema)` to create a new message.
 */
export const WeatherConditionsSchema: GenMessage<WeatherConditions> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 2);

/**
 * @generated from message engine.v1.OperationResult
 */
export type OperationResult = Message<"engine.v1.OperationResult"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message engine.v1.OperationResult.
 * Use `create(OperationResultSchema)` to create a new message.
 */
export const OperationResultSchema: GenMessage<OperationResult> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 3);

/**
 * ── Movement ──────────────────────────────────────────────────────────────────
 * A single geographic point in a movement route.
 *
 * @generated from message engine.v1.Waypoint
 */
export type Waypoint = Message<"engine.v1.Waypoint"> & {
  /**
   * @generated from field: double lat = 1;
   */
  lat: number;

  /**
   * @generated from field: double lon = 2;
   */
  lon: number;

  /**
   * @generated from field: double alt_msl = 3;
   */
  altMsl: number;

  /**
   * @generated from field: string h3_cell = 4;
   */
  h3Cell: string;

  /**
   * @generated from field: string h3_parent_cell = 5;
   */
  h3ParentCell: string;
};

/**
 * Describes the message engine.v1.Waypoint.
 * Use `create(WaypointSchema)` to create a new message.
 */
export const WaypointSchema: GenMessage<Waypoint> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 4);

/**
 * An ordered list of waypoints describing a unit's intended route.
 * The first waypoint is the current destination; subsequent waypoints
 * are queued and visited in order.
 *
 * @generated from message engine.v1.MoveOrder
 */
export type MoveOrder = Message<"engine.v1.MoveOrder"> & {
  /**
   * @generated from field: repeated engine.v1.Waypoint waypoints = 1;
   */
  waypoints: Waypoint[];

  /**
   * @generated from field: bool auto_generated = 2;
   */
  autoGenerated: boolean;
};

/**
 * Describes the message engine.v1.MoveOrder.
 * Use `create(MoveOrderSchema)` to create a new message.
 */
export const MoveOrderSchema: GenMessage<MoveOrder> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 5);

/**
 * @generated from enum engine.v1.WeatherState
 */
export enum WeatherState {
  /**
   * @generated from enum value: WEATHER_UNSPECIFIED = 0;
   */
  WEATHER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: WEATHER_CLEAR = 1;
   */
  WEATHER_CLEAR = 1,

  /**
   * @generated from enum value: WEATHER_OVERCAST = 2;
   */
  WEATHER_OVERCAST = 2,

  /**
   * @generated from enum value: WEATHER_FOG = 3;
   */
  WEATHER_FOG = 3,

  /**
   * @generated from enum value: WEATHER_RAIN = 4;
   */
  WEATHER_RAIN = 4,

  /**
   * @generated from enum value: WEATHER_HEAVY_RAIN = 5;
   */
  WEATHER_HEAVY_RAIN = 5,

  /**
   * @generated from enum value: WEATHER_SNOW = 6;
   */
  WEATHER_SNOW = 6,

  /**
   * @generated from enum value: WEATHER_BLIZZARD = 7;
   */
  WEATHER_BLIZZARD = 7,
}

/**
 * Describes the enum engine.v1.WeatherState.
 */
export const WeatherStateSchema: GenEnum<WeatherState> = /*@__PURE__*/
  enumDesc(file_engine_v1_common, 0);

/**
 * @generated from enum engine.v1.UnitDomain
 */
export enum UnitDomain {
  /**
   * @generated from enum value: DOMAIN_UNSPECIFIED = 0;
   */
  DOMAIN_UNSPECIFIED = 0,

  /**
   * @generated from enum value: DOMAIN_LAND = 1;
   */
  DOMAIN_LAND = 1,

  /**
   * @generated from enum value: DOMAIN_AIR = 2;
   */
  DOMAIN_AIR = 2,

  /**
   * @generated from enum value: DOMAIN_SEA = 3;
   */
  DOMAIN_SEA = 3,

  /**
   * @generated from enum value: DOMAIN_SUBSURFACE = 4;
   */
  DOMAIN_SUBSURFACE = 4,
}

/**
 * Describes the enum engine.v1.UnitDomain.
 */
export const UnitDomainSchema: GenEnum<UnitDomain> = /*@__PURE__*/
  enumDesc(file_engine_v1_common, 1);

/**
 * @generated from enum engine.v1.FormationPosture
 */
export enum FormationPosture {
  /**
   * @generated from enum value: POSTURE_UNSPECIFIED = 0;
   */
  POSTURE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: POSTURE_TRAVELING = 1;
   */
  POSTURE_TRAVELING = 1,

  /**
   * @generated from enum value: POSTURE_BOUNDING = 2;
   */
  POSTURE_BOUNDING = 2,

  /**
   * @generated from enum value: POSTURE_DELIBERATE = 3;
   */
  POSTURE_DELIBERATE = 3,

  /**
   * @generated from enum value: POSTURE_HASTY_DEFENSE = 4;
   */
  POSTURE_HASTY_DEFENSE = 4,

  /**
   * @generated from enum value: POSTURE_DUG_IN = 5;
   */
  POSTURE_DUG_IN = 5,

  /**
   * @generated from enum value: POSTURE_DISPERSED = 6;
   */
  POSTURE_DISPERSED = 6,

  /**
   * @generated from enum value: POSTURE_ASSAULT = 7;
   */
  POSTURE_ASSAULT = 7,
}

/**
 * Describes the enum engine.v1.FormationPosture.
 */
export const FormationPostureSchema: GenEnum<FormationPosture> = /*@__PURE__*/
  enumDesc(file_engine_v1_common, 2);

