// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/common.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/common.proto.
 */
export const file_engine_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvY29tbW9uLnByb3RvEgllbmdpbmUudjEiVQoIUG9zaXRpb24SCwoDbGF0GAEgASgBEgsKA2xvbhgCIAEoARIPCgdhbHRfbXNsGAMgASgBEg8KB2hlYWRpbmcYBCABKAESDQoFc3BlZWQYBSABKAEiZQoHUG9seWdvbhIlCgh2ZXJ0aWNlcxgBIAMoCzITLmVuZ2luZS52MS5Qb3NpdGlvbhINCgVsYWJlbBgCIAEoCRIkCgR0eXBlGAMgASgOMhYuZW5naW5lLnYxLlBvbHlnb25UeXBlIjcKB1NpbVRpbWUSFwoPc2Vjb25kc19lbGFwc2VkGAEgASgBEhMKC3RpY2tfbnVtYmVyGAIgASgDIrEBChFXZWF0aGVyQ29uZGl0aW9ucxImCgVzdGF0ZRgBIAEoDjIXLmVuZ2luZS52MS5XZWF0aGVyU3RhdGUSFQoNdmlzaWJpbGl0eV9rbRgCIAEoAhIWCg53aW5kX3NwZWVkX21wcxgDIAEoAhIVCg1wcmVjaXBpdGF0aW9uGAQgASgIEhUKDXRlbXBlcmF0dXJlX2MYBSABKAISFwoPY2xvdWRfY2VpbGluZ19tGAYgASgCIjEKD09wZXJhdGlvblJlc3VsdBIPCgdzdWNjZXNzGAEgASgIEg0KBWVycm9yGAIgASgJKoACCgtQb2x5Z29uVHlwZRIcChhQT0xZR09OX1RZUEVfVU5TUEVDSUZJRUQQABIcChhQT0xZR09OX1RZUEVfQVJFQV9PRl9PUFMQARIaChZQT0xZR09OX1RZUEVfT0JKRUNUSVZFEAISIAocUE9MWUdPTl9UWVBFX0VOR0FHRU1FTlRfWk9ORRADEh0KGVBPTFlHT05fVFlQRV9OT19GSVJFX1pPTkUQBBIaChZQT0xZR09OX1RZUEVfTUlORUZJRUxEEAUSHwobUE9MWUdPTl9UWVBFX0VYQ0xVU0lPTl9aT05FEAYSGwoXUE9MWUdPTl9UWVBFX1JFQ09OX1pPTkUQByrdAQoLVGVycmFpblR5cGUSFwoTVEVSUkFJTl9VTlNQRUNJRklFRBAAEhAKDFRFUlJBSU5fT1BFThABEhEKDVRFUlJBSU5fVVJCQU4QAhISCg5URVJSQUlOX0ZPUkVTVBADEhEKDVRFUlJBSU5fSElMTFMQBBIVChFURVJSQUlOX01PVU5UQUlOUxAFEhQKEFRFUlJBSU5fV0VUTEFORFMQBhIRCg1URVJSQUlOX0NPQVNUEAcSFQoRVEVSUkFJTl9SSVZFUkxJTkUQCBISCg5URVJSQUlOX0RFU0VSVBAJKrcBCgxXZWF0aGVyU3RhdGUSFwoTV0VBVEhFUl9VTlNQRUNJRklFRBAAEhEKDVdFQVRIRVJfQ0xFQVIQARIUChBXRUFUSEVSX09WRVJDQVNUEAISEAoMV0VBVEhFUl9SQUlOEAMSEAoMV0VBVEhFUl9TTk9XEAQSDwoLV0VBVEhFUl9GT0cQBRIWChJXRUFUSEVSX0RVU1RfU1RPUk0QBhIYChRXRUFUSEVSX1RIVU5ERVJTVE9STRAHQitaKWdpdGh1Yi5jb20vYXJlc3NpbS9pbnRlcm5hbC9nZW4vZW5naW5lL3YxYgZwcm90bzM");

/**
 * WGS84 position. The canonical coordinate type for all geospatial fields.
 *
 * @generated from message engine.v1.Position
 */
export type Position = Message<"engine.v1.Position"> & {
  /**
   * Decimal degrees, -90 to +90
   *
   * @generated from field: double lat = 1;
   */
  lat: number;

  /**
   * Decimal degrees, -180 to +180
   *
   * @generated from field: double lon = 2;
   */
  lon: number;

  /**
   * Meters above mean sea level
   *
   * @generated from field: double alt_msl = 3;
   */
  altMsl: number;

  /**
   * True north bearing, 0–360 degrees
   *
   * @generated from field: double heading = 4;
   */
  heading: number;

  /**
   * Current speed, meters per second
   *
   * @generated from field: double speed = 5;
   */
  speed: number;
};

/**
 * Describes the message engine.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 0);

/**
 * A bounding polygon for areas of operations, objectives, engagement zones, etc.
 *
 * @generated from message engine.v1.Polygon
 */
export type Polygon = Message<"engine.v1.Polygon"> & {
  /**
   * @generated from field: repeated engine.v1.Position vertices = 1;
   */
  vertices: Position[];

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: engine.v1.PolygonType type = 3;
   */
  type: PolygonType;
};

/**
 * Describes the message engine.v1.Polygon.
 * Use `create(PolygonSchema)` to create a new message.
 */
export const PolygonSchema: GenMessage<Polygon> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 1);

/**
 * Simulation-internal time reference. Decoupled from wall-clock time so that
 * time-scale changes (fast-forward, pause) do not affect determinism.
 *
 * @generated from message engine.v1.SimTime
 */
export type SimTime = Message<"engine.v1.SimTime"> & {
  /**
   * Seconds since scenario start
   *
   * @generated from field: double seconds_elapsed = 1;
   */
  secondsElapsed: number;

  /**
   * Absolute tick counter (monotonically increasing)
   *
   * @generated from field: int64 tick_number = 2;
   */
  tickNumber: bigint;
};

/**
 * Describes the message engine.v1.SimTime.
 * Use `create(SimTimeSchema)` to create a new message.
 */
export const SimTimeSchema: GenMessage<SimTime> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 2);

/**
 * Environmental conditions. Affects sensor performance, aviation, and weapon
 * accuracy. Shared by combat.proto, scenario.proto, and events.proto.
 *
 * @generated from message engine.v1.WeatherConditions
 */
export type WeatherConditions = Message<"engine.v1.WeatherConditions"> & {
  /**
   * @generated from field: engine.v1.WeatherState state = 1;
   */
  state: WeatherState;

  /**
   * Optical line-of-sight in kilometers
   *
   * @generated from field: float visibility_km = 2;
   */
  visibilityKm: number;

  /**
   * Affects smoke drift, aircraft stability
   *
   * @generated from field: float wind_speed_mps = 3;
   */
  windSpeedMps: number;

  /**
   * Degrades optical sensors, affects aviation
   *
   * @generated from field: bool precipitation = 4;
   */
  precipitation: boolean;

  /**
   * Celsius; affects engine starts at extremes
   *
   * @generated from field: float temperature_c = 5;
   */
  temperatureC: number;

  /**
   * Meters AGL; limits fixed-wing CAS
   *
   * @generated from field: float cloud_ceiling_m = 6;
   */
  cloudCeilingM: number;
};

/**
 * Describes the message engine.v1.WeatherConditions.
 * Use `create(WeatherConditionsSchema)` to create a new message.
 */
export const WeatherConditionsSchema: GenMessage<WeatherConditions> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 3);

/**
 * Standardized result wrapper for adjudicator operations exposed over the
 * Wails bridge. Keeps error handling uniform across all bridge methods.
 *
 * @generated from message engine.v1.OperationResult
 */
export type OperationResult = Message<"engine.v1.OperationResult"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * Empty string on success
   *
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message engine.v1.OperationResult.
 * Use `create(OperationResultSchema)` to create a new message.
 */
export const OperationResultSchema: GenMessage<OperationResult> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 4);

/**
 * @generated from enum engine.v1.PolygonType
 */
export enum PolygonType {
  /**
   * @generated from enum value: POLYGON_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POLYGON_TYPE_AREA_OF_OPS = 1;
   */
  AREA_OF_OPS = 1,

  /**
   * @generated from enum value: POLYGON_TYPE_OBJECTIVE = 2;
   */
  OBJECTIVE = 2,

  /**
   * @generated from enum value: POLYGON_TYPE_ENGAGEMENT_ZONE = 3;
   */
  ENGAGEMENT_ZONE = 3,

  /**
   * @generated from enum value: POLYGON_TYPE_NO_FIRE_ZONE = 4;
   */
  NO_FIRE_ZONE = 4,

  /**
   * @generated from enum value: POLYGON_TYPE_MINEFIELD = 5;
   */
  MINEFIELD = 5,

  /**
   * @generated from enum value: POLYGON_TYPE_EXCLUSION_ZONE = 6;
   */
  EXCLUSION_ZONE = 6,

  /**
   * @generated from enum value: POLYGON_TYPE_RECON_ZONE = 7;
   */
  RECON_ZONE = 7,
}

/**
 * Describes the enum engine.v1.PolygonType.
 */
export const PolygonTypeSchema: GenEnum<PolygonType> = /*@__PURE__*/
  enumDesc(file_engine_v1_common, 0);

/**
 * Terrain type at a given position. Used as a modifier input in combat
 * resolution and as a movement speed selector. The adjudicator looks up terrain
 * from the map layer at a unit's current position each tick.
 *
 * @generated from enum engine.v1.TerrainType
 */
export enum TerrainType {
  /**
   * @generated from enum value: TERRAIN_UNSPECIFIED = 0;
   */
  TERRAIN_UNSPECIFIED = 0,

  /**
   * Fields, steppe, desert — no protection bonus
   *
   * @generated from enum value: TERRAIN_OPEN = 1;
   */
  TERRAIN_OPEN = 1,

  /**
   * Built-up areas: high protection for defenders
   *
   * @generated from enum value: TERRAIN_URBAN = 2;
   */
  TERRAIN_URBAN = 2,

  /**
   * Concealment, moderate protection, slows vehicles
   *
   * @generated from enum value: TERRAIN_FOREST = 3;
   */
  TERRAIN_FOREST = 3,

  /**
   * Observation advantage, hull-down positions
   *
   * @generated from enum value: TERRAIN_HILLS = 4;
   */
  TERRAIN_HILLS = 4,

  /**
   * Strong defense, near-impassable to vehicles
   *
   * @generated from enum value: TERRAIN_MOUNTAINS = 5;
   */
  TERRAIN_MOUNTAINS = 5,

  /**
   * Canalized movement, poor for armor
   *
   * @generated from enum value: TERRAIN_WETLANDS = 6;
   */
  TERRAIN_WETLANDS = 6,

  /**
   * Littoral: sea/land transition
   *
   * @generated from enum value: TERRAIN_COAST = 7;
   */
  TERRAIN_COAST = 7,

  /**
   * Major crossing obstacle
   *
   * @generated from enum value: TERRAIN_RIVERLINE = 8;
   */
  TERRAIN_RIVERLINE = 8,

  /**
   * Open, poor cover, extreme temperature effects
   *
   * @generated from enum value: TERRAIN_DESERT = 9;
   */
  TERRAIN_DESERT = 9,
}

/**
 * Describes the enum engine.v1.TerrainType.
 */
export const TerrainTypeSchema: GenEnum<TerrainType> = /*@__PURE__*/
  enumDesc(file_engine_v1_common, 1);

/**
 * @generated from enum engine.v1.WeatherState
 */
export enum WeatherState {
  /**
   * @generated from enum value: WEATHER_UNSPECIFIED = 0;
   */
  WEATHER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: WEATHER_CLEAR = 1;
   */
  WEATHER_CLEAR = 1,

  /**
   * @generated from enum value: WEATHER_OVERCAST = 2;
   */
  WEATHER_OVERCAST = 2,

  /**
   * @generated from enum value: WEATHER_RAIN = 3;
   */
  WEATHER_RAIN = 3,

  /**
   * @generated from enum value: WEATHER_SNOW = 4;
   */
  WEATHER_SNOW = 4,

  /**
   * Severe optical degradation
   *
   * @generated from enum value: WEATHER_FOG = 5;
   */
  WEATHER_FOG = 5,

  /**
   * Severe: radar and optical both degraded
   *
   * @generated from enum value: WEATHER_DUST_STORM = 6;
   */
  WEATHER_DUST_STORM = 6,

  /**
   * @generated from enum value: WEATHER_THUNDERSTORM = 7;
   */
  WEATHER_THUNDERSTORM = 7,
}

/**
 * Describes the enum engine.v1.WeatherState.
 */
export const WeatherStateSchema: GenEnum<WeatherState> = /*@__PURE__*/
  enumDesc(file_engine_v1_common, 2);

