// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/common.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/common.proto.
 */
export const file_engine_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvY29tbW9uLnByb3RvEgllbmdpbmUudjEiVQoIUG9zaXRpb24SCwoDbGF0GAEgASgBEgsKA2xvbhgCIAEoARIPCgdhbHRfbXNsGAMgASgBEg8KB2hlYWRpbmcYBCABKAESDQoFc3BlZWQYBSABKAEiNwoHU2ltVGltZRIXCg9zZWNvbmRzX2VsYXBzZWQYASABKAESEwoLdGlja19udW1iZXIYAiABKAMisQEKEVdlYXRoZXJDb25kaXRpb25zEiYKBXN0YXRlGAEgASgOMhcuZW5naW5lLnYxLldlYXRoZXJTdGF0ZRIVCg12aXNpYmlsaXR5X2ttGAIgASgCEhYKDndpbmRfc3BlZWRfbXBzGAMgASgCEhUKDXByZWNpcGl0YXRpb24YBCABKAgSFQoNdGVtcGVyYXR1cmVfYxgFIAEoAhIXCg9jbG91ZF9jZWlsaW5nX20YBiABKAIiMQoPT3BlcmF0aW9uUmVzdWx0Eg8KB3N1Y2Nlc3MYASABKAgSDQoFZXJyb3IYAiABKAkqswEKDFdlYXRoZXJTdGF0ZRIXChNXRUFUSEVSX1VOU1BFQ0lGSUVEEAASEQoNV0VBVEhFUl9DTEVBUhABEhQKEFdFQVRIRVJfT1ZFUkNBU1QQAhIPCgtXRUFUSEVSX0ZPRxADEhAKDFdFQVRIRVJfUkFJThAEEhYKEldFQVRIRVJfSEVBVllfUkFJThAFEhAKDFdFQVRIRVJfU05PVxAGEhQKEFdFQVRIRVJfQkxJWlpBUkQQB0IrWilnaXRodWIuY29tL2FyZXNzaW0vaW50ZXJuYWwvZ2VuL2VuZ2luZS92MWIGcHJvdG8z");

/**
 * @generated from message engine.v1.Position
 */
export type Position = Message<"engine.v1.Position"> & {
  /**
   * Decimal degrees -90..+90
   *
   * @generated from field: double lat = 1;
   */
  lat: number;

  /**
   * Decimal degrees -180..+180
   *
   * @generated from field: double lon = 2;
   */
  lon: number;

  /**
   * Meters above mean sea level
   *
   * @generated from field: double alt_msl = 3;
   */
  altMsl: number;

  /**
   * True north bearing 0–360°
   *
   * @generated from field: double heading = 4;
   */
  heading: number;

  /**
   * Meters per second
   *
   * @generated from field: double speed = 5;
   */
  speed: number;
};

/**
 * Describes the message engine.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 0);

/**
 * @generated from message engine.v1.SimTime
 */
export type SimTime = Message<"engine.v1.SimTime"> & {
  /**
   * @generated from field: double seconds_elapsed = 1;
   */
  secondsElapsed: number;

  /**
   * @generated from field: int64 tick_number = 2;
   */
  tickNumber: bigint;
};

/**
 * Describes the message engine.v1.SimTime.
 * Use `create(SimTimeSchema)` to create a new message.
 */
export const SimTimeSchema: GenMessage<SimTime> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 1);

/**
 * @generated from message engine.v1.WeatherConditions
 */
export type WeatherConditions = Message<"engine.v1.WeatherConditions"> & {
  /**
   * @generated from field: engine.v1.WeatherState state = 1;
   */
  state: WeatherState;

  /**
   * @generated from field: float visibility_km = 2;
   */
  visibilityKm: number;

  /**
   * @generated from field: float wind_speed_mps = 3;
   */
  windSpeedMps: number;

  /**
   * @generated from field: bool precipitation = 4;
   */
  precipitation: boolean;

  /**
   * @generated from field: float temperature_c = 5;
   */
  temperatureC: number;

  /**
   * @generated from field: float cloud_ceiling_m = 6;
   */
  cloudCeilingM: number;
};

/**
 * Describes the message engine.v1.WeatherConditions.
 * Use `create(WeatherConditionsSchema)` to create a new message.
 */
export const WeatherConditionsSchema: GenMessage<WeatherConditions> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 2);

/**
 * @generated from message engine.v1.OperationResult
 */
export type OperationResult = Message<"engine.v1.OperationResult"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message engine.v1.OperationResult.
 * Use `create(OperationResultSchema)` to create a new message.
 */
export const OperationResultSchema: GenMessage<OperationResult> = /*@__PURE__*/
  messageDesc(file_engine_v1_common, 3);

/**
 * @generated from enum engine.v1.WeatherState
 */
export enum WeatherState {
  /**
   * @generated from enum value: WEATHER_UNSPECIFIED = 0;
   */
  WEATHER_UNSPECIFIED = 0,

  /**
   * @generated from enum value: WEATHER_CLEAR = 1;
   */
  WEATHER_CLEAR = 1,

  /**
   * @generated from enum value: WEATHER_OVERCAST = 2;
   */
  WEATHER_OVERCAST = 2,

  /**
   * @generated from enum value: WEATHER_FOG = 3;
   */
  WEATHER_FOG = 3,

  /**
   * @generated from enum value: WEATHER_RAIN = 4;
   */
  WEATHER_RAIN = 4,

  /**
   * @generated from enum value: WEATHER_HEAVY_RAIN = 5;
   */
  WEATHER_HEAVY_RAIN = 5,

  /**
   * @generated from enum value: WEATHER_SNOW = 6;
   */
  WEATHER_SNOW = 6,

  /**
   * @generated from enum value: WEATHER_BLIZZARD = 7;
   */
  WEATHER_BLIZZARD = 7,
}

/**
 * Describes the enum engine.v1.WeatherState.
 */
export const WeatherStateSchema: GenEnum<WeatherState> = /*@__PURE__*/
  enumDesc(file_engine_v1_common, 0);

