// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/events.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Position, SimTime, WeatherConditions } from "./common_pb";
import { file_engine_v1_common } from "./common_pb";
import type { FormationPosture, Unit } from "./unit_pb";
import { file_engine_v1_unit } from "./unit_pb";
import type { OperationalStatus } from "./status_pb";
import { file_engine_v1_status } from "./status_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/events.proto.
 */
export const file_engine_v1_events: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvZXZlbnRzLnByb3RvEgllbmdpbmUudjEinwEKEUZ1bGxTdGF0ZVNuYXBzaG90Eh4KBXVuaXRzGAEgAygLMg8uZW5naW5lLnYxLlVuaXQSJAoIc2ltX3RpbWUYAyABKAsyEi5lbmdpbmUudjEuU2ltVGltZRItCgd3ZWF0aGVyGAQgASgLMhwuZW5naW5lLnYxLldlYXRoZXJDb25kaXRpb25zEhUKDXNjZW5hcmlvX25hbWUYBSABKAkiVQoSU2NlbmFyaW9TdGF0ZUV2ZW50EisKBXN0YXRlGAEgASgOMhwuZW5naW5lLnYxLlNjZW5hcmlvUGxheVN0YXRlEhIKCnRpbWVfc2NhbGUYAiABKAIiXQoPQmF0Y2hVbml0VXBkYXRlEiQKBmRlbHRhcxgBIAMoCzIULmVuZ2luZS52MS5Vbml0RGVsdGESJAoIc2ltX3RpbWUYAiABKAsyEi5lbmdpbmUudjEuU2ltVGltZSKfAQoJVW5pdERlbHRhEg8KB3VuaXRfaWQYASABKAkSJQoIcG9zaXRpb24YAiABKAsyEy5lbmdpbmUudjEuUG9zaXRpb24SLAoGc3RhdHVzGAMgASgLMhwuZW5naW5lLnYxLk9wZXJhdGlvbmFsU3RhdHVzEiwKB3Bvc3R1cmUYBCABKA4yGy5lbmdpbmUudjEuRm9ybWF0aW9uUG9zdHVyZSJXChBVbml0U3Bhd25lZEV2ZW50Eh0KBHVuaXQYASABKAsyDy5lbmdpbmUudjEuVW5pdBIkCghzaW1fdGltZRgCIAEoCzISLmVuZ2luZS52MS5TaW1UaW1lIloKElVuaXREZXN0cm95ZWRFdmVudBIPCgd1bml0X2lkGAEgASgJEg0KBWNhdXNlGAIgASgJEiQKCHNpbV90aW1lGAMgASgLMhIuZW5naW5lLnYxLlNpbVRpbWUiTwoOTmFycmF0aXZlRXZlbnQSDAoEdGV4dBgBIAEoCRIQCghjYXRlZ29yeRgCIAEoCRIPCgd1bml0X2lkGAMgASgJEgwKBHNpZGUYBCABKAkqbAoRU2NlbmFyaW9QbGF5U3RhdGUSGAoUU0NFTkFSSU9fVU5TUEVDSUZJRUQQABITCg9TQ0VOQVJJT19QQVVTRUQQARIUChBTQ0VOQVJJT19SVU5OSU5HEAISEgoOU0NFTkFSSU9fRU5ERUQQA0IrWilnaXRodWIuY29tL2FyZXNzaW0vaW50ZXJuYWwvZ2VuL2VuZ2luZS92MWIGcHJvdG8z", [file_engine_v1_common, file_engine_v1_unit, file_engine_v1_status]);

/**
 * @generated from message engine.v1.FullStateSnapshot
 */
export type FullStateSnapshot = Message<"engine.v1.FullStateSnapshot"> & {
  /**
   * @generated from field: repeated engine.v1.Unit units = 1;
   */
  units: Unit[];

  /**
   * @generated from field: engine.v1.SimTime sim_time = 3;
   */
  simTime?: SimTime;

  /**
   * @generated from field: engine.v1.WeatherConditions weather = 4;
   */
  weather?: WeatherConditions;

  /**
   * @generated from field: string scenario_name = 5;
   */
  scenarioName: string;
};

/**
 * Describes the message engine.v1.FullStateSnapshot.
 * Use `create(FullStateSnapshotSchema)` to create a new message.
 */
export const FullStateSnapshotSchema: GenMessage<FullStateSnapshot> = /*@__PURE__*/
  messageDesc(file_engine_v1_events, 0);

/**
 * @generated from message engine.v1.ScenarioStateEvent
 */
export type ScenarioStateEvent = Message<"engine.v1.ScenarioStateEvent"> & {
  /**
   * @generated from field: engine.v1.ScenarioPlayState state = 1;
   */
  state: ScenarioPlayState;

  /**
   * @generated from field: float time_scale = 2;
   */
  timeScale: number;
};

/**
 * Describes the message engine.v1.ScenarioStateEvent.
 * Use `create(ScenarioStateEventSchema)` to create a new message.
 */
export const ScenarioStateEventSchema: GenMessage<ScenarioStateEvent> = /*@__PURE__*/
  messageDesc(file_engine_v1_events, 1);

/**
 * @generated from message engine.v1.BatchUnitUpdate
 */
export type BatchUnitUpdate = Message<"engine.v1.BatchUnitUpdate"> & {
  /**
   * @generated from field: repeated engine.v1.UnitDelta deltas = 1;
   */
  deltas: UnitDelta[];

  /**
   * @generated from field: engine.v1.SimTime sim_time = 2;
   */
  simTime?: SimTime;
};

/**
 * Describes the message engine.v1.BatchUnitUpdate.
 * Use `create(BatchUnitUpdateSchema)` to create a new message.
 */
export const BatchUnitUpdateSchema: GenMessage<BatchUnitUpdate> = /*@__PURE__*/
  messageDesc(file_engine_v1_events, 2);

/**
 * @generated from message engine.v1.UnitDelta
 */
export type UnitDelta = Message<"engine.v1.UnitDelta"> & {
  /**
   * @generated from field: string unit_id = 1;
   */
  unitId: string;

  /**
   * present if unit moved
   *
   * @generated from field: engine.v1.Position position = 2;
   */
  position?: Position;

  /**
   * present if status changed
   *
   * @generated from field: engine.v1.OperationalStatus status = 3;
   */
  status?: OperationalStatus;

  /**
   * present if posture changed
   *
   * @generated from field: engine.v1.FormationPosture posture = 4;
   */
  posture: FormationPosture;
};

/**
 * Describes the message engine.v1.UnitDelta.
 * Use `create(UnitDeltaSchema)` to create a new message.
 */
export const UnitDeltaSchema: GenMessage<UnitDelta> = /*@__PURE__*/
  messageDesc(file_engine_v1_events, 3);

/**
 * @generated from message engine.v1.UnitSpawnedEvent
 */
export type UnitSpawnedEvent = Message<"engine.v1.UnitSpawnedEvent"> & {
  /**
   * @generated from field: engine.v1.Unit unit = 1;
   */
  unit?: Unit;

  /**
   * @generated from field: engine.v1.SimTime sim_time = 2;
   */
  simTime?: SimTime;
};

/**
 * Describes the message engine.v1.UnitSpawnedEvent.
 * Use `create(UnitSpawnedEventSchema)` to create a new message.
 */
export const UnitSpawnedEventSchema: GenMessage<UnitSpawnedEvent> = /*@__PURE__*/
  messageDesc(file_engine_v1_events, 4);

/**
 * @generated from message engine.v1.UnitDestroyedEvent
 */
export type UnitDestroyedEvent = Message<"engine.v1.UnitDestroyedEvent"> & {
  /**
   * @generated from field: string unit_id = 1;
   */
  unitId: string;

  /**
   * "combat" | "withdrawal" | "scenario"
   *
   * @generated from field: string cause = 2;
   */
  cause: string;

  /**
   * @generated from field: engine.v1.SimTime sim_time = 3;
   */
  simTime?: SimTime;
};

/**
 * Describes the message engine.v1.UnitDestroyedEvent.
 * Use `create(UnitDestroyedEventSchema)` to create a new message.
 */
export const UnitDestroyedEventSchema: GenMessage<UnitDestroyedEvent> = /*@__PURE__*/
  messageDesc(file_engine_v1_events, 5);

/**
 * @generated from message engine.v1.NarrativeEvent
 */
export type NarrativeEvent = Message<"engine.v1.NarrativeEvent"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * "combat" | "scenario" | "c2"
   *
   * @generated from field: string category = 2;
   */
  category: string;

  /**
   * @generated from field: string unit_id = 3;
   */
  unitId: string;

  /**
   * @generated from field: string side = 4;
   */
  side: string;
};

/**
 * Describes the message engine.v1.NarrativeEvent.
 * Use `create(NarrativeEventSchema)` to create a new message.
 */
export const NarrativeEventSchema: GenMessage<NarrativeEvent> = /*@__PURE__*/
  messageDesc(file_engine_v1_events, 6);

/**
 * @generated from enum engine.v1.ScenarioPlayState
 */
export enum ScenarioPlayState {
  /**
   * @generated from enum value: SCENARIO_UNSPECIFIED = 0;
   */
  SCENARIO_UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCENARIO_PAUSED = 1;
   */
  SCENARIO_PAUSED = 1,

  /**
   * @generated from enum value: SCENARIO_RUNNING = 2;
   */
  SCENARIO_RUNNING = 2,

  /**
   * @generated from enum value: SCENARIO_ENDED = 3;
   */
  SCENARIO_ENDED = 3,
}

/**
 * Describes the enum engine.v1.ScenarioPlayState.
 */
export const ScenarioPlayStateSchema: GenEnum<ScenarioPlayState> = /*@__PURE__*/
  enumDesc(file_engine_v1_events, 0);

