// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/logistics.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Position } from "./common_pb";
import { file_engine_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/logistics.proto.
 */
export const file_engine_v1_logistics: GenFile = /*@__PURE__*/
  fileDesc("ChllbmdpbmUvdjEvbG9naXN0aWNzLnByb3RvEgllbmdpbmUudjEiiwMKDUxvZ2lzdGljc05vZGUSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIMCgRzaWRlGAMgASgJEhEKCW5hdGlvbl9pZBgEIAEoCRIqCgR0eXBlGAUgASgOMhwuZW5naW5lLnYxLkxvZ2lzdGljc05vZGVUeXBlEiUKCHBvc2l0aW9uGAYgASgLMhMuZW5naW5lLnYxLlBvc2l0aW9uEi4KCGNhcGFjaXR5GAcgASgLMhwuZW5naW5lLnYxLkxvZ2lzdGljc0NhcGFjaXR5EjMKDWN1cnJlbnRfc3RvY2sYCCABKAsyHC5lbmdpbmUudjEuTG9naXN0aWNzQ2FwYWNpdHkSGgoScmVwbGVuaXNobWVudF9yYXRlGAkgASgCEhYKDnBhcmVudF9ub2RlX2lkGAogASgJEg4KBmhlYWx0aBgLIAEoAhIRCglpc19hY3RpdmUYDCABKAgSEwoLaXNfc3VwcGxpZWQYDSABKAgSGwoTc3RyYXRlZ2ljX3NvdXJjZV9pZBgOIAEoCSKBAQoRTG9naXN0aWNzQ2FwYWNpdHkSEwoLZnVlbF9saXRlcnMYASABKAISEgoKYW1tb191bml0cxgCIAEoAhIUCgxmb29kX3JhdGlvbnMYAyABKAISEwoLc3BhcmVfcGFydHMYBCABKAISGAoQbWVkaWNhbF9zdXBwbGllcxgFIAEoAiLjAQoKU3VwcGx5TGluaxIKCgJpZBgBIAEoCRIPCgdmcm9tX2lkGAIgASgJEg0KBXRvX2lkGAMgASgJEiwKCWxpbmtfdHlwZRgEIAEoDjIZLmVuZ2luZS52MS5TdXBwbHlMaW5rVHlwZRIRCgliYW5kd2lkdGgYBSABKAISEAoIbGVuZ3RoX20YBiABKAISEQoJaXNfYWN0aXZlGAcgASgIEhYKDmlzX2ludGVyZGljdGVkGAggASgIEhUKDXZ1bG5lcmFiaWxpdHkYCSABKAISFAoMY29tbW9kaXR5X2lkGAogASgJKukBChFMb2dpc3RpY3NOb2RlVHlwZRIZChVMT0dJU1RJQ1NfVU5TUEVDSUZJRUQQABIdChlMT0dJU1RJQ1NfU1RSQVRFR0lDX0RFUE9UEAESGQoVTE9HSVNUSUNTX0JSSUdBREVfQlNBEAISHgoaTE9HSVNUSUNTX0JBVFRBTElPTl9UUkFJTlMQAxIcChhMT0dJU1RJQ1NfRk9SV0FSRF9TVVBQTFkQBBIWChJMT0dJU1RJQ1NfQUlSRklFTEQQBRISCg5MT0dJU1RJQ1NfUE9SVBAGEhUKEUxPR0lTVElDU19NRURJQ0FMEAcqnQEKDlN1cHBseUxpbmtUeXBlEhsKF1NVUFBMWV9MSU5LX1VOU1BFQ0lGSUVEEAASFAoQU1VQUExZX0xJTktfUk9BRBABEhQKEFNVUFBMWV9MSU5LX1JBSUwQAhITCg9TVVBQTFlfTElOS19BSVIQAxITCg9TVVBQTFlfTElOS19TRUEQBBIYChRTVVBQTFlfTElOS19QSVBFTElORRAFQitaKWdpdGh1Yi5jb20vYXJlc3NpbS9pbnRlcm5hbC9nZW4vZW5naW5lL3YxYgZwcm90bzM", [file_engine_v1_common]);

/**
 * A logistics node is the physical anchor of the supply chain.
 * Types span the full logistics hierarchy from theater-level strategic depots
 * down to battalion-level forward supply points.
 *
 * @generated from message engine.v1.LogisticsNode
 */
export type LogisticsNode = Message<"engine.v1.LogisticsNode"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * e.g. "47th BSB BSA", "Depot Bravo"
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string side = 3;
   */
  side: string;

  /**
   * Phase 3: owning nation
   *
   * @generated from field: string nation_id = 4;
   */
  nationId: string;

  /**
   * @generated from field: engine.v1.LogisticsNodeType type = 5;
   */
  type: LogisticsNodeType;

  /**
   * @generated from field: engine.v1.Position position = 6;
   */
  position?: Position;

  /**
   * Maximum stock levels
   *
   * @generated from field: engine.v1.LogisticsCapacity capacity = 7;
   */
  capacity?: LogisticsCapacity;

  /**
   * Current on-hand quantities
   *
   * @generated from field: engine.v1.LogisticsCapacity current_stock = 8;
   */
  currentStock?: LogisticsCapacity;

  /**
   * Supply units per sim-hour received from higher
   *
   * @generated from field: float replenishment_rate = 9;
   */
  replenishmentRate: number;

  /**
   * ID of higher logistics node in the chain
   *
   * @generated from field: string parent_node_id = 10;
   */
  parentNodeId: string;

  /**
   * 0.0–1.0; reduced if node is attacked
   *
   * @generated from field: float health = 11;
   */
  health: number;

  /**
   * @generated from field: bool is_active = 12;
   */
  isActive: boolean;

  /**
   * Connectivity: the node can only supply units if it is itself supplied.
   * Computed by supply resolution graph traversal.
   *
   * @generated from field: bool is_supplied = 13;
   */
  isSupplied: boolean;

  /**
   * Phase 3: ID of the InfrastructureNode or Nation supplying this node.
   *
   * @generated from field: string strategic_source_id = 14;
   */
  strategicSourceId: string;
};

/**
 * Describes the message engine.v1.LogisticsNode.
 * Use `create(LogisticsNodeSchema)` to create a new message.
 */
export const LogisticsNodeSchema: GenMessage<LogisticsNode> = /*@__PURE__*/
  messageDesc(file_engine_v1_logistics, 0);

/**
 * Stock quantities for each supply category.
 * Kept at a coarse level in Phase 1 (abstracted "ammo units").
 * Phase 3: each field maps 1:1 to a commodity_id in strategic.proto for
 * precise stock accounting at the national level.
 *
 * @generated from message engine.v1.LogisticsCapacity
 */
export type LogisticsCapacity = Message<"engine.v1.LogisticsCapacity"> & {
  /**
   * All fuel types (abstracted in Phase 1)
   *
   * @generated from field: float fuel_liters = 1;
   */
  fuelLiters: number;

  /**
   * 1 unit = enough ammo for 1 company to fight for 1 day
   *
   * @generated from field: float ammo_units = 2;
   */
  ammoUnits: number;

  /**
   * Person-days of rations
   *
   * @generated from field: float food_rations = 3;
   */
  foodRations: number;

  /**
   * Abstracted maintenance points (Phase 3: specific parts)
   *
   * @generated from field: float spare_parts = 4;
   */
  spareParts: number;

  /**
   * @generated from field: float medical_supplies = 5;
   */
  medicalSupplies: number;
};

/**
 * Describes the message engine.v1.LogisticsCapacity.
 * Use `create(LogisticsCapacitySchema)` to create a new message.
 */
export const LogisticsCapacitySchema: GenMessage<LogisticsCapacity> = /*@__PURE__*/
  messageDesc(file_engine_v1_logistics, 1);

/**
 * A directed supply link between two nodes, or a node and a unit.
 * Stored as a graph edge in SurrealDB: supply_link TYPE RELATION FROM ... TO ...
 * The adjudicator evaluates interdiction and bandwidth each supply tick.
 *
 * @generated from message engine.v1.SupplyLink
 */
export type SupplyLink = Message<"engine.v1.SupplyLink"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Source: LogisticsNode.id or Unit.id
   *
   * @generated from field: string from_id = 2;
   */
  fromId: string;

  /**
   * Destination: LogisticsNode.id or Unit.id
   *
   * @generated from field: string to_id = 3;
   */
  toId: string;

  /**
   * @generated from field: engine.v1.SupplyLinkType link_type = 4;
   */
  linkType: SupplyLinkType;

  /**
   * Supply units per sim-hour this link can carry
   *
   * @generated from field: float bandwidth = 5;
   */
  bandwidth: number;

  /**
   * Route length in meters
   *
   * @generated from field: float length_m = 6;
   */
  lengthM: number;

  /**
   * False = route physically closed (destroyed bridge, etc.)
   *
   * @generated from field: bool is_active = 7;
   */
  isActive: boolean;

  /**
   * True = enemy fires or maneuver have cut the route
   *
   * @generated from field: bool is_interdicted = 8;
   */
  isInterdicted: boolean;

  /**
   * Vulnerability score used to compute interdiction probability each tick.
   * Higher values = easier to cut (e.g., single-bridge routes, exposed roads).
   *
   * 0.0–1.0
   *
   * @generated from field: float vulnerability = 9;
   */
  vulnerability: number;

  /**
   * Phase 3: which commodity this link carries (empty = all types)
   *
   * @generated from field: string commodity_id = 10;
   */
  commodityId: string;
};

/**
 * Describes the message engine.v1.SupplyLink.
 * Use `create(SupplyLinkSchema)` to create a new message.
 */
export const SupplyLinkSchema: GenMessage<SupplyLink> = /*@__PURE__*/
  messageDesc(file_engine_v1_logistics, 2);

/**
 * @generated from enum engine.v1.LogisticsNodeType
 */
export enum LogisticsNodeType {
  /**
   * @generated from enum value: LOGISTICS_UNSPECIFIED = 0;
   */
  LOGISTICS_UNSPECIFIED = 0,

  /**
   * Theater/corps-level; receives from production
   *
   * @generated from enum value: LOGISTICS_STRATEGIC_DEPOT = 1;
   */
  LOGISTICS_STRATEGIC_DEPOT = 1,

  /**
   * Brigade Support Area
   *
   * @generated from enum value: LOGISTICS_BRIGADE_BSA = 2;
   */
  LOGISTICS_BRIGADE_BSA = 2,

  /**
   * Battalion-level trains
   *
   * @generated from enum value: LOGISTICS_BATTALION_TRAINS = 3;
   */
  LOGISTICS_BATTALION_TRAINS = 3,

  /**
   * Forward supply point; closest to line of contact
   *
   * @generated from enum value: LOGISTICS_FORWARD_SUPPLY = 4;
   */
  LOGISTICS_FORWARD_SUPPLY = 4,

  /**
   * Aviation fuel and ordnance hub
   *
   * @generated from enum value: LOGISTICS_AIRFIELD = 5;
   */
  LOGISTICS_AIRFIELD = 5,

  /**
   * Maritime resupply hub
   *
   * @generated from enum value: LOGISTICS_PORT = 6;
   */
  LOGISTICS_PORT = 6,

  /**
   * CASEVAC, level II/III medical treatment
   *
   * @generated from enum value: LOGISTICS_MEDICAL = 7;
   */
  LOGISTICS_MEDICAL = 7,
}

/**
 * Describes the enum engine.v1.LogisticsNodeType.
 */
export const LogisticsNodeTypeSchema: GenEnum<LogisticsNodeType> = /*@__PURE__*/
  enumDesc(file_engine_v1_logistics, 0);

/**
 * @generated from enum engine.v1.SupplyLinkType
 */
export enum SupplyLinkType {
  /**
   * @generated from enum value: SUPPLY_LINK_UNSPECIFIED = 0;
   */
  SUPPLY_LINK_UNSPECIFIED = 0,

  /**
   * Truck convoy on improved road (MSR/ASR)
   *
   * @generated from enum value: SUPPLY_LINK_ROAD = 1;
   */
  SUPPLY_LINK_ROAD = 1,

  /**
   * Rail line; high bandwidth, fixed route
   *
   * @generated from enum value: SUPPLY_LINK_RAIL = 2;
   */
  SUPPLY_LINK_RAIL = 2,

  /**
   * Fixed-wing or helicopter resupply
   *
   * @generated from enum value: SUPPLY_LINK_AIR = 3;
   */
  SUPPLY_LINK_AIR = 3,

  /**
   * Maritime; requires functioning port on both ends
   *
   * @generated from enum value: SUPPLY_LINK_SEA = 4;
   */
  SUPPLY_LINK_SEA = 4,

  /**
   * Phase 3: fuel only; highest bandwidth per unit
   *
   * @generated from enum value: SUPPLY_LINK_PIPELINE = 5;
   */
  SUPPLY_LINK_PIPELINE = 5,
}

/**
 * Describes the enum engine.v1.SupplyLinkType.
 */
export const SupplyLinkTypeSchema: GenEnum<SupplyLinkType> = /*@__PURE__*/
  enumDesc(file_engine_v1_logistics, 1);

