// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/scenario.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { WeatherConditions } from "./common_pb";
import { file_engine_v1_common } from "./common_pb";
import type { Unit } from "./unit_pb";
import { file_engine_v1_unit } from "./unit_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/scenario.proto.
 */
export const file_engine_v1_scenario: GenFile = /*@__PURE__*/
  fileDesc("ChhlbmdpbmUvdjEvc2NlbmFyaW8ucHJvdG8SCWVuZ2luZS52MSKBAgoTQ291bnRyeVJlbGF0aW9uc2hpcBIUCgxmcm9tX2NvdW50cnkYASABKAkSEgoKdG9fY291bnRyeRgCIAEoCRITCgtzaGFyZV9pbnRlbBgDIAEoCBIgChhhaXJzcGFjZV90cmFuc2l0X2FsbG93ZWQYBCABKAgSHwoXYWlyc3BhY2Vfc3RyaWtlX2FsbG93ZWQYBSABKAgSJQodZGVmZW5zaXZlX3Bvc2l0aW9uaW5nX2FsbG93ZWQYBiABKAgSIAoYbWFyaXRpbWVfdHJhbnNpdF9hbGxvd2VkGAcgASgIEh8KF21hcml0aW1lX3N0cmlrZV9hbGxvd2VkGAggASgIIrgCCghTY2VuYXJpbxIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhYKDmNsYXNzaWZpY2F0aW9uGAQgASgJEg4KBmF1dGhvchgFIAEoCRIXCg9zdGFydF90aW1lX3VuaXgYBiABKAESDwoHdmVyc2lvbhgHIAEoCRIvCghzZXR0aW5ncxgIIAEoCzIdLmVuZ2luZS52MS5TaW11bGF0aW9uU2V0dGluZ3MSIwoDbWFwGAkgASgLMhYuZW5naW5lLnYxLk1hcFNldHRpbmdzEh4KBXVuaXRzGAsgAygLMg8uZW5naW5lLnYxLlVuaXQSNQoNcmVsYXRpb25zaGlwcxgMIAMoCzIeLmVuZ2luZS52MS5Db3VudHJ5UmVsYXRpb25zaGlwIj4KElNpbXVsYXRpb25TZXR0aW5ncxIUCgx0aWNrX3JhdGVfaHoYASABKAISEgoKdGltZV9zY2FsZRgCIAEoAiJECgtNYXBTZXR0aW5ncxI1Cg9pbml0aWFsX3dlYXRoZXIYBCABKAsyHC5lbmdpbmUudjEuV2VhdGhlckNvbmRpdGlvbnMqdgoRQWRqdWRpY2F0aW9uTW9kZWwSGQoVQURKX01PREVMX1VOU1BFQ0lGSUVEEAASFQoRQURKX01PREVMX0RFRkFVTFQQARISCg5BREpfTU9ERUxfRkFTVBACEhsKF0FESl9NT0RFTF9ISUdIX0ZJREVMSVRZEANCK1opZ2l0aHViLmNvbS9hcmVzc2ltL2ludGVybmFsL2dlbi9lbmdpbmUvdjFiBnByb3RvMw", [file_engine_v1_common, file_engine_v1_unit]);

/**
 * @generated from message engine.v1.CountryRelationship
 */
export type CountryRelationship = Message<"engine.v1.CountryRelationship"> & {
  /**
   * @generated from field: string from_country = 1;
   */
  fromCountry: string;

  /**
   * @generated from field: string to_country = 2;
   */
  toCountry: string;

  /**
   * @generated from field: bool share_intel = 3;
   */
  shareIntel: boolean;

  /**
   * @generated from field: bool airspace_transit_allowed = 4;
   */
  airspaceTransitAllowed: boolean;

  /**
   * @generated from field: bool airspace_strike_allowed = 5;
   */
  airspaceStrikeAllowed: boolean;

  /**
   * @generated from field: bool defensive_positioning_allowed = 6;
   */
  defensivePositioningAllowed: boolean;

  /**
   * @generated from field: bool maritime_transit_allowed = 7;
   */
  maritimeTransitAllowed: boolean;

  /**
   * @generated from field: bool maritime_strike_allowed = 8;
   */
  maritimeStrikeAllowed: boolean;
};

/**
 * Describes the message engine.v1.CountryRelationship.
 * Use `create(CountryRelationshipSchema)` to create a new message.
 */
export const CountryRelationshipSchema: GenMessage<CountryRelationship> = /*@__PURE__*/
  messageDesc(file_engine_v1_scenario, 0);

/**
 * @generated from message engine.v1.Scenario
 */
export type Scenario = Message<"engine.v1.Scenario"> & {
  /**
   * UUID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string classification = 4;
   */
  classification: string;

  /**
   * @generated from field: string author = 5;
   */
  author: string;

  /**
   * @generated from field: double start_time_unix = 6;
   */
  startTimeUnix: number;

  /**
   * @generated from field: string version = 7;
   */
  version: string;

  /**
   * @generated from field: engine.v1.SimulationSettings settings = 8;
   */
  settings?: SimulationSettings;

  /**
   * @generated from field: engine.v1.MapSettings map = 9;
   */
  map?: MapSettings;

  /**
   * @generated from field: repeated engine.v1.Unit units = 11;
   */
  units: Unit[];

  /**
   * @generated from field: repeated engine.v1.CountryRelationship relationships = 12;
   */
  relationships: CountryRelationship[];
};

/**
 * Describes the message engine.v1.Scenario.
 * Use `create(ScenarioSchema)` to create a new message.
 */
export const ScenarioSchema: GenMessage<Scenario> = /*@__PURE__*/
  messageDesc(file_engine_v1_scenario, 1);

/**
 * @generated from message engine.v1.SimulationSettings
 */
export type SimulationSettings = Message<"engine.v1.SimulationSettings"> & {
  /**
   * Adjudicator ticks per wall-second (default 10)
   *
   * @generated from field: float tick_rate_hz = 1;
   */
  tickRateHz: number;

  /**
   * Sim-seconds per wall-second (default 1.0)
   *
   * @generated from field: float time_scale = 2;
   */
  timeScale: number;
};

/**
 * Describes the message engine.v1.SimulationSettings.
 * Use `create(SimulationSettingsSchema)` to create a new message.
 */
export const SimulationSettingsSchema: GenMessage<SimulationSettings> = /*@__PURE__*/
  messageDesc(file_engine_v1_scenario, 2);

/**
 * @generated from message engine.v1.MapSettings
 */
export type MapSettings = Message<"engine.v1.MapSettings"> & {
  /**
   * @generated from field: engine.v1.WeatherConditions initial_weather = 4;
   */
  initialWeather?: WeatherConditions;
};

/**
 * Describes the message engine.v1.MapSettings.
 * Use `create(MapSettingsSchema)` to create a new message.
 */
export const MapSettingsSchema: GenMessage<MapSettings> = /*@__PURE__*/
  messageDesc(file_engine_v1_scenario, 3);

/**
 * @generated from enum engine.v1.AdjudicationModel
 */
export enum AdjudicationModel {
  /**
   * @generated from enum value: ADJ_MODEL_UNSPECIFIED = 0;
   */
  ADJ_MODEL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ADJ_MODEL_DEFAULT = 1;
   */
  ADJ_MODEL_DEFAULT = 1,

  /**
   * @generated from enum value: ADJ_MODEL_FAST = 2;
   */
  ADJ_MODEL_FAST = 2,

  /**
   * @generated from enum value: ADJ_MODEL_HIGH_FIDELITY = 3;
   */
  ADJ_MODEL_HIGH_FIDELITY = 3,
}

/**
 * Describes the enum engine.v1.AdjudicationModel.
 */
export const AdjudicationModelSchema: GenEnum<AdjudicationModel> = /*@__PURE__*/
  enumDesc(file_engine_v1_scenario, 0);

