// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/status.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/status.proto.
 */
export const file_engine_v1_status: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvc3RhdHVzLnByb3RvEgllbmdpbmUudjEi6gEKEU9wZXJhdGlvbmFsU3RhdHVzEhoKEnBlcnNvbm5lbF9zdHJlbmd0aBgBIAEoAhIaChJlcXVpcG1lbnRfc3RyZW5ndGgYAiABKAISHAoUY29tYmF0X2VmZmVjdGl2ZW5lc3MYAyABKAISGQoRZnVlbF9sZXZlbF9saXRlcnMYBSABKAISDgoGbW9yYWxlGAggASgCEg8KB2ZhdGlndWUYCSABKAISEQoJaXNfYWN0aXZlGA4gASgIEjAKDmNvbWJhdF9lZmZlY3RzGA8gASgLMhguZW5naW5lLnYxLkNvbWJhdEVmZmVjdHMiRwoNQ29tYmF0RWZmZWN0cxISCgpzdXBwcmVzc2VkGAEgASgIEhEKCWRpc3J1cHRlZBgDIAEoCBIPCgdyb3V0aW5nGAUgASgIQitaKWdpdGh1Yi5jb20vYXJlc3NpbS9pbnRlcm5hbC9nZW4vZW5naW5lL3YxYgZwcm90bzM");

/**
 * Current operational health of a unit. Updated each tick by the adjudicator.
 *
 * @generated from message engine.v1.OperationalStatus
 */
export type OperationalStatus = Message<"engine.v1.OperationalStatus"> & {
  /**
   * 0.0–1.0 fraction of authorised strength
   *
   * @generated from field: float personnel_strength = 1;
   */
  personnelStrength: number;

  /**
   * 0.0–1.0 fraction of organic equipment
   *
   * @generated from field: float equipment_strength = 2;
   */
  equipmentStrength: number;

  /**
   * Derived composite score 0.0–1.0
   *
   * @generated from field: float combat_effectiveness = 3;
   */
  combatEffectiveness: number;

  /**
   * @generated from field: float fuel_level_liters = 5;
   */
  fuelLevelLiters: number;

  /**
   * 0.0–1.0
   *
   * @generated from field: float morale = 8;
   */
  morale: number;

  /**
   * 0.0–1.0; high fatigue degrades effectiveness
   *
   * @generated from field: float fatigue = 9;
   */
  fatigue: number;

  /**
   * false = destroyed / withdrawn
   *
   * @generated from field: bool is_active = 14;
   */
  isActive: boolean;

  /**
   * @generated from field: engine.v1.CombatEffects combat_effects = 15;
   */
  combatEffects?: CombatEffects;
};

/**
 * Describes the message engine.v1.OperationalStatus.
 * Use `create(OperationalStatusSchema)` to create a new message.
 */
export const OperationalStatusSchema: GenMessage<OperationalStatus> = /*@__PURE__*/
  messageDesc(file_engine_v1_status, 0);

/**
 * Transient combat states applied by the adjudicator.
 *
 * @generated from message engine.v1.CombatEffects
 */
export type CombatEffects = Message<"engine.v1.CombatEffects"> & {
  /**
   * Unit cannot initiate fire
   *
   * @generated from field: bool suppressed = 1;
   */
  suppressed: boolean;

  /**
   * Formation broken, movement penalty
   *
   * @generated from field: bool disrupted = 3;
   */
  disrupted: boolean;

  /**
   * Fleeing; control lost
   *
   * @generated from field: bool routing = 5;
   */
  routing: boolean;
};

/**
 * Describes the message engine.v1.CombatEffects.
 * Use `create(CombatEffectsSchema)` to create a new message.
 */
export const CombatEffectsSchema: GenMessage<CombatEffects> = /*@__PURE__*/
  messageDesc(file_engine_v1_status, 1);

