// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/weapon.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { UnitDomain } from "./common_pb";
import { file_engine_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/weapon.proto.
 */
export const file_engine_v1_weapon: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvd2VhcG9uLnByb3RvEgllbmdpbmUudjEijQIKEFdlYXBvbkRlZmluaXRpb24SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRItCg5kb21haW5fdGFyZ2V0cxgEIAMoDjIVLmVuZ2luZS52MS5Vbml0RG9tYWluEhEKCXNwZWVkX21wcxgFIAEoAhIPCgdyYW5nZV9tGAYgASgCEhoKEnByb2JhYmlsaXR5X29mX2hpdBgHIAEoAhIpCghndWlkYW5jZRgIIAEoDjIXLmVuZ2luZS52MS5HdWlkYW5jZVR5cGUSMAoLZWZmZWN0X3R5cGUYCSABKA4yGy5lbmdpbmUudjEuV2VhcG9uRWZmZWN0VHlwZSJGCgtXZWFwb25TdGF0ZRIRCgl3ZWFwb25faWQYASABKAkSEwoLY3VycmVudF9xdHkYAiABKAUSDwoHbWF4X3F0eRgDIAEoBSqxAQoMR3VpZGFuY2VUeXBlEhgKFEdVSURBTkNFX1VOU1BFQ0lGSUVEEAASFQoRR1VJREFOQ0VfVU5HVUlERUQQARIQCgxHVUlEQU5DRV9HUFMQAhISCg5HVUlEQU5DRV9SQURBUhADEg8KC0dVSURBTkNFX0lSEAQSEgoOR1VJREFOQ0VfTEFTRVIQBRIRCg1HVUlEQU5DRV9XSVJFEAYSEgoOR1VJREFOQ0VfU09OQVIQByrqAgoQV2VhcG9uRWZmZWN0VHlwZRIiCh5XRUFQT05fRUZGRUNUX1RZUEVfVU5TUEVDSUZJRUQQABIfChtXRUFQT05fRUZGRUNUX1RZUEVfQU5USV9BSVIQARIgChxXRUFQT05fRUZGRUNUX1RZUEVfQU5USV9TSElQEAISIQodV0VBUE9OX0VGRkVDVF9UWVBFX0FOVElfQVJNT1IQAxIiCh5XRUFQT05fRUZGRUNUX1RZUEVfTEFORF9TVFJJS0UQBBIbChdXRUFQT05fRUZGRUNUX1RZUEVfU0VBRBAFEicKI1dFQVBPTl9FRkZFQ1RfVFlQRV9CQUxMSVNUSUNfU1RSSUtFEAYSIgoeV0VBUE9OX0VGRkVDVF9UWVBFX0lOVEVSQ0VQVE9SEAcSHgoaV0VBUE9OX0VGRkVDVF9UWVBFX0dVTkZJUkUQCBIeChpXRUFQT05fRUZGRUNUX1RZUEVfVE9SUEVETxAJQitaKWdpdGh1Yi5jb20vYXJlc3NpbS9pbnRlcm5hbC9nZW4vZW5naW5lL3YxYgZwcm90bzM", [file_engine_v1_common]);

/**
 * @generated from message engine.v1.WeaponDefinition
 */
export type WeaponDefinition = Message<"engine.v1.WeaponDefinition"> & {
  /**
   * Slug, e.g. "aam-aim120c-amraam"
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Display name, e.g. "AIM-120C AMRAAM"
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Domains this weapon can engage. A weapon that cannot engage a domain is
   * ignored when the adjudicator checks engagements against that domain.
   *
   * @generated from field: repeated engine.v1.UnitDomain domain_targets = 4;
   */
  domainTargets: UnitDomain[];

  /**
   * Ballistic / kinematic parameters.
   *
   * Projectile/missile speed in m/s
   *
   * @generated from field: float speed_mps = 5;
   */
  speedMps: number;

  /**
   * Maximum effective range in metres
   *
   * @generated from field: float range_m = 6;
   */
  rangeM: number;

  /**
   * 0–1; base probability, range-degraded at fire time
   *
   * @generated from field: float probability_of_hit = 7;
   */
  probabilityOfHit: number;

  /**
   * Guidance mechanism; determines tracking behaviour in AdvanceMunitions.
   *
   * @generated from field: engine.v1.GuidanceType guidance = 8;
   */
  guidance: GuidanceType;

  /**
   * @generated from field: engine.v1.WeaponEffectType effect_type = 9;
   */
  effectType: WeaponEffectType;
};

/**
 * Describes the message engine.v1.WeaponDefinition.
 * Use `create(WeaponDefinitionSchema)` to create a new message.
 */
export const WeaponDefinitionSchema: GenMessage<WeaponDefinition> = /*@__PURE__*/
  messageDesc(file_engine_v1_weapon, 0);

/**
 * @generated from message engine.v1.WeaponState
 */
export type WeaponState = Message<"engine.v1.WeaponState"> & {
  /**
   * Foreign key → WeaponDefinition.id
   *
   * @generated from field: string weapon_id = 1;
   */
  weaponId: string;

  /**
   * Rounds/missiles remaining
   *
   * @generated from field: int32 current_qty = 2;
   */
  currentQty: number;

  /**
   * Maximum the platform can carry (from loadout)
   *
   * @generated from field: int32 max_qty = 3;
   */
  maxQty: number;
};

/**
 * Describes the message engine.v1.WeaponState.
 * Use `create(WeaponStateSchema)` to create a new message.
 */
export const WeaponStateSchema: GenMessage<WeaponState> = /*@__PURE__*/
  messageDesc(file_engine_v1_weapon, 1);

/**
 * @generated from enum engine.v1.GuidanceType
 */
export enum GuidanceType {
  /**
   * @generated from enum value: GUIDANCE_UNSPECIFIED = 0;
   */
  GUIDANCE_UNSPECIFIED = 0,

  /**
   * Ballistic / dumb-fire — fixed point at launch
   *
   * @generated from enum value: GUIDANCE_UNGUIDED = 1;
   */
  GUIDANCE_UNGUIDED = 1,

  /**
   * GPS/INS precision — fixed point, high accuracy
   *
   * @generated from enum value: GUIDANCE_GPS = 2;
   */
  GUIDANCE_GPS = 2,

  /**
   * Active radar homing — tracks while shooter holds lock
   *
   * @generated from enum value: GUIDANCE_RADAR = 3;
   */
  GUIDANCE_RADAR = 3,

  /**
   * Infrared seeker — fire-and-forget, always tracks
   *
   * @generated from enum value: GUIDANCE_IR = 4;
   */
  GUIDANCE_IR = 4,

  /**
   * Laser-guided — tracks illuminated spot (fixed point)
   *
   * @generated from enum value: GUIDANCE_LASER = 5;
   */
  GUIDANCE_LASER = 5,

  /**
   * Wire / datalink-guided — operator tracks continuously
   *
   * @generated from enum value: GUIDANCE_WIRE = 6;
   */
  GUIDANCE_WIRE = 6,

  /**
   * Acoustic sonar — torpedo self-homing, always tracks
   *
   * @generated from enum value: GUIDANCE_SONAR = 7;
   */
  GUIDANCE_SONAR = 7,
}

/**
 * Describes the enum engine.v1.GuidanceType.
 */
export const GuidanceTypeSchema: GenEnum<GuidanceType> = /*@__PURE__*/
  enumDesc(file_engine_v1_weapon, 0);

/**
 * @generated from enum engine.v1.WeaponEffectType
 */
export enum WeaponEffectType {
  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_ANTI_AIR = 1;
   */
  ANTI_AIR = 1,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_ANTI_SHIP = 2;
   */
  ANTI_SHIP = 2,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_ANTI_ARMOR = 3;
   */
  ANTI_ARMOR = 3,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_LAND_STRIKE = 4;
   */
  LAND_STRIKE = 4,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_SEAD = 5;
   */
  SEAD = 5,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_BALLISTIC_STRIKE = 6;
   */
  BALLISTIC_STRIKE = 6,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_INTERCEPTOR = 7;
   */
  INTERCEPTOR = 7,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_GUNFIRE = 8;
   */
  GUNFIRE = 8,

  /**
   * @generated from enum value: WEAPON_EFFECT_TYPE_TORPEDO = 9;
   */
  TORPEDO = 9,
}

/**
 * Describes the enum engine.v1.WeaponEffectType.
 */
export const WeaponEffectTypeSchema: GenEnum<WeaponEffectType> = /*@__PURE__*/
  enumDesc(file_engine_v1_weapon, 1);

