// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/weapon.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { UnitDomain } from "./common_pb";
import { file_engine_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/weapon.proto.
 */
export const file_engine_v1_weapon: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvd2VhcG9uLnByb3RvEgllbmdpbmUudjEi2wEKEFdlYXBvbkRlZmluaXRpb24SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRItCg5kb21haW5fdGFyZ2V0cxgEIAMoDjIVLmVuZ2luZS52MS5Vbml0RG9tYWluEhEKCXNwZWVkX21wcxgFIAEoAhIPCgdyYW5nZV9tGAYgASgCEhoKEnByb2JhYmlsaXR5X29mX2hpdBgHIAEoAhIpCghndWlkYW5jZRgIIAEoDjIXLmVuZ2luZS52MS5HdWlkYW5jZVR5cGUiRgoLV2VhcG9uU3RhdGUSEQoJd2VhcG9uX2lkGAEgASgJEhMKC2N1cnJlbnRfcXR5GAIgASgFEg8KB21heF9xdHkYAyABKAUqsQEKDEd1aWRhbmNlVHlwZRIYChRHVUlEQU5DRV9VTlNQRUNJRklFRBAAEhUKEUdVSURBTkNFX1VOR1VJREVEEAESEAoMR1VJREFOQ0VfR1BTEAISEgoOR1VJREFOQ0VfUkFEQVIQAxIPCgtHVUlEQU5DRV9JUhAEEhIKDkdVSURBTkNFX0xBU0VSEAUSEQoNR1VJREFOQ0VfV0lSRRAGEhIKDkdVSURBTkNFX1NPTkFSEAdCK1opZ2l0aHViLmNvbS9hcmVzc2ltL2ludGVybmFsL2dlbi9lbmdpbmUvdjFiBnByb3RvMw", [file_engine_v1_common]);

/**
 * @generated from message engine.v1.WeaponDefinition
 */
export type WeaponDefinition = Message<"engine.v1.WeaponDefinition"> & {
  /**
   * Slug, e.g. "aam-aim120c-amraam"
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Display name, e.g. "AIM-120C AMRAAM"
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Domains this weapon can engage. A weapon that cannot engage a domain is
   * ignored when the adjudicator checks engagements against that domain.
   *
   * @generated from field: repeated engine.v1.UnitDomain domain_targets = 4;
   */
  domainTargets: UnitDomain[];

  /**
   * Ballistic / kinematic parameters.
   *
   * Projectile/missile speed in m/s
   *
   * @generated from field: float speed_mps = 5;
   */
  speedMps: number;

  /**
   * Maximum effective range in metres
   *
   * @generated from field: float range_m = 6;
   */
  rangeM: number;

  /**
   * 0–1; base probability, range-degraded at fire time
   *
   * @generated from field: float probability_of_hit = 7;
   */
  probabilityOfHit: number;

  /**
   * Guidance mechanism; determines tracking behaviour in AdvanceMunitions.
   *
   * @generated from field: engine.v1.GuidanceType guidance = 8;
   */
  guidance: GuidanceType;
};

/**
 * Describes the message engine.v1.WeaponDefinition.
 * Use `create(WeaponDefinitionSchema)` to create a new message.
 */
export const WeaponDefinitionSchema: GenMessage<WeaponDefinition> = /*@__PURE__*/
  messageDesc(file_engine_v1_weapon, 0);

/**
 * @generated from message engine.v1.WeaponState
 */
export type WeaponState = Message<"engine.v1.WeaponState"> & {
  /**
   * Foreign key → WeaponDefinition.id
   *
   * @generated from field: string weapon_id = 1;
   */
  weaponId: string;

  /**
   * Rounds/missiles remaining
   *
   * @generated from field: int32 current_qty = 2;
   */
  currentQty: number;

  /**
   * Maximum the platform can carry (from loadout)
   *
   * @generated from field: int32 max_qty = 3;
   */
  maxQty: number;
};

/**
 * Describes the message engine.v1.WeaponState.
 * Use `create(WeaponStateSchema)` to create a new message.
 */
export const WeaponStateSchema: GenMessage<WeaponState> = /*@__PURE__*/
  messageDesc(file_engine_v1_weapon, 1);

/**
 * @generated from enum engine.v1.GuidanceType
 */
export enum GuidanceType {
  /**
   * @generated from enum value: GUIDANCE_UNSPECIFIED = 0;
   */
  GUIDANCE_UNSPECIFIED = 0,

  /**
   * Ballistic / dumb-fire — fixed point at launch
   *
   * @generated from enum value: GUIDANCE_UNGUIDED = 1;
   */
  GUIDANCE_UNGUIDED = 1,

  /**
   * GPS/INS precision — fixed point, high accuracy
   *
   * @generated from enum value: GUIDANCE_GPS = 2;
   */
  GUIDANCE_GPS = 2,

  /**
   * Active radar homing — tracks while shooter holds lock
   *
   * @generated from enum value: GUIDANCE_RADAR = 3;
   */
  GUIDANCE_RADAR = 3,

  /**
   * Infrared seeker — fire-and-forget, always tracks
   *
   * @generated from enum value: GUIDANCE_IR = 4;
   */
  GUIDANCE_IR = 4,

  /**
   * Laser-guided — tracks illuminated spot (fixed point)
   *
   * @generated from enum value: GUIDANCE_LASER = 5;
   */
  GUIDANCE_LASER = 5,

  /**
   * Wire / datalink-guided — operator tracks continuously
   *
   * @generated from enum value: GUIDANCE_WIRE = 6;
   */
  GUIDANCE_WIRE = 6,

  /**
   * Acoustic sonar — torpedo self-homing, always tracks
   *
   * @generated from enum value: GUIDANCE_SONAR = 7;
   */
  GUIDANCE_SONAR = 7,
}

/**
 * Describes the enum engine.v1.GuidanceType.
 */
export const GuidanceTypeSchema: GenEnum<GuidanceType> = /*@__PURE__*/
  enumDesc(file_engine_v1_weapon, 0);

