// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file engine/v1/weapon.proto (package engine.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { UnitDomain } from "./common_pb";
import { file_engine_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file engine/v1/weapon.proto.
 */
export const file_engine_v1_weapon: GenFile = /*@__PURE__*/
  fileDesc("ChZlbmdpbmUvdjEvd2VhcG9uLnByb3RvEgllbmdpbmUudjEisAEKEFdlYXBvbkRlZmluaXRpb24SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRItCg5kb21haW5fdGFyZ2V0cxgEIAMoDjIVLmVuZ2luZS52MS5Vbml0RG9tYWluEhEKCXNwZWVkX21wcxgFIAEoAhIPCgdyYW5nZV9tGAYgASgCEhoKEnByb2JhYmlsaXR5X29mX2hpdBgHIAEoAiJGCgtXZWFwb25TdGF0ZRIRCgl3ZWFwb25faWQYASABKAkSEwoLY3VycmVudF9xdHkYAiABKAUSDwoHbWF4X3F0eRgDIAEoBUIrWilnaXRodWIuY29tL2FyZXNzaW0vaW50ZXJuYWwvZ2VuL2VuZ2luZS92MWIGcHJvdG8z", [file_engine_v1_common]);

/**
 * @generated from message engine.v1.WeaponDefinition
 */
export type WeaponDefinition = Message<"engine.v1.WeaponDefinition"> & {
  /**
   * Slug, e.g. "aam-aim120c-amraam"
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Display name, e.g. "AIM-120C AMRAAM"
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Domains this weapon can engage. A weapon that cannot engage a domain is
   * ignored when the adjudicator checks engagements against that domain.
   *
   * @generated from field: repeated engine.v1.UnitDomain domain_targets = 4;
   */
  domainTargets: UnitDomain[];

  /**
   * Ballistic / kinematic parameters.
   *
   * Projectile/missile speed in m/s
   *
   * @generated from field: float speed_mps = 5;
   */
  speedMps: number;

  /**
   * Maximum effective range in metres
   *
   * @generated from field: float range_m = 6;
   */
  rangeM: number;

  /**
   * 0–1; uniform across all target types for now
   *
   * @generated from field: float probability_of_hit = 7;
   */
  probabilityOfHit: number;
};

/**
 * Describes the message engine.v1.WeaponDefinition.
 * Use `create(WeaponDefinitionSchema)` to create a new message.
 */
export const WeaponDefinitionSchema: GenMessage<WeaponDefinition> = /*@__PURE__*/
  messageDesc(file_engine_v1_weapon, 0);

/**
 * @generated from message engine.v1.WeaponState
 */
export type WeaponState = Message<"engine.v1.WeaponState"> & {
  /**
   * Foreign key → WeaponDefinition.id
   *
   * @generated from field: string weapon_id = 1;
   */
  weaponId: string;

  /**
   * Rounds/missiles remaining
   *
   * @generated from field: int32 current_qty = 2;
   */
  currentQty: number;

  /**
   * Maximum the platform can carry (from loadout)
   *
   * @generated from field: int32 max_qty = 3;
   */
  maxQty: number;
};

/**
 * Describes the message engine.v1.WeaponState.
 * Use `create(WeaponStateSchema)` to create a new message.
 */
export const WeaponStateSchema: GenMessage<WeaponState> = /*@__PURE__*/
  messageDesc(file_engine_v1_weapon, 1);

