// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendMoveWaypoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendMoveWaypoint'](arg1, arg2, arg3);
}

export function CancelMoveOrder(arg1) {
  return window['go']['main']['App']['CancelMoveOrder'](arg1);
}

export function DeleteScenario(arg1) {
  return window['go']['main']['App']['DeleteScenario'](arg1);
}

export function DeleteUnitDefinition(arg1) {
  return window['go']['main']['App']['DeleteUnitDefinition'](arg1);
}

export function GetScenario(arg1) {
  return window['go']['main']['App']['GetScenario'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListScenarios() {
  return window['go']['main']['App']['ListScenarios']();
}

export function ListUnitDefinitions() {
  return window['go']['main']['App']['ListUnitDefinitions']();
}

export function ListWeaponDefinitions() {
  return window['go']['main']['App']['ListWeaponDefinitions']();
}

export function LoadScenarioFromProto(arg1) {
  return window['go']['main']['App']['LoadScenarioFromProto'](arg1);
}

export function MoveUnit(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveUnit'](arg1, arg2, arg3);
}

export function PauseSim(arg1) {
  return window['go']['main']['App']['PauseSim'](arg1);
}

export function PreviewCurrentEngagement(arg1) {
  return window['go']['main']['App']['PreviewCurrentEngagement'](arg1);
}

export function PreviewCurrentRelationships() {
  return window['go']['main']['App']['PreviewCurrentRelationships']();
}

export function PreviewCurrentStrikePath(arg1) {
  return window['go']['main']['App']['PreviewCurrentStrikePath'](arg1);
}

export function PreviewCurrentTransitPath(arg1) {
  return window['go']['main']['App']['PreviewCurrentTransitPath'](arg1);
}

export function PreviewDraftPlacement(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['PreviewDraftPlacement'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function PreviewDraftRelationships(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewDraftRelationships'](arg1, arg2, arg3);
}

export function PreviewDraftStrikePath(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PreviewDraftStrikePath'](arg1, arg2, arg3, arg4, arg5);
}

export function PreviewDraftTransitPath(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PreviewDraftTransitPath'](arg1, arg2, arg3, arg4, arg5);
}

export function PreviewEngagementOptions(arg1) {
  return window['go']['main']['App']['PreviewEngagementOptions'](arg1);
}

export function PreviewEngagementOptionsForLoadout(arg1, arg2) {
  return window['go']['main']['App']['PreviewEngagementOptionsForLoadout'](arg1, arg2);
}

export function PreviewTargetEngagementOptions(arg1, arg2) {
  return window['go']['main']['App']['PreviewTargetEngagementOptions'](arg1, arg2);
}

export function PreviewTargetEngagementSummary(arg1, arg2) {
  return window['go']['main']['App']['PreviewTargetEngagementSummary'](arg1, arg2);
}

export function RemoveMoveWaypoint(arg1, arg2) {
  return window['go']['main']['App']['RemoveMoveWaypoint'](arg1, arg2);
}

export function RequestSync() {
  return window['go']['main']['App']['RequestSync']();
}

export function SaveScenario(arg1) {
  return window['go']['main']['App']['SaveScenario'](arg1);
}

export function SaveUnitDefinition(arg1) {
  return window['go']['main']['App']['SaveUnitDefinition'](arg1);
}

export function SetCountryRelationship(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SetCountryRelationship'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SetHumanControlledTeam(arg1) {
  return window['go']['main']['App']['SetHumanControlledTeam'](arg1);
}

export function SetIntelSharing(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIntelSharing'](arg1, arg2, arg3);
}

export function SetSimSpeed(arg1) {
  return window['go']['main']['App']['SetSimSpeed'](arg1);
}

export function SetUnitAttackOrder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetUnitAttackOrder'](arg1, arg2, arg3, arg4, arg5);
}

export function SetUnitEngagement(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetUnitEngagement'](arg1, arg2, arg3);
}

export function SetUnitLoadoutConfiguration(arg1, arg2) {
  return window['go']['main']['App']['SetUnitLoadoutConfiguration'](arg1, arg2);
}

export function UpdateMoveWaypoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMoveWaypoint'](arg1, arg2, arg3, arg4);
}
