// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetVersion():Promise<string>;

export function ListScenarios():Promise<Array<Record<string, any>>>;

export function LoadScenarioFromProto(arg1:string):Promise<main.BridgeResult>;

export function PauseSim(arg1:boolean):Promise<main.BridgeResult>;

export function RequestSync():Promise<main.BridgeResult>;

export function SetSimSpeed(arg1:number):Promise<main.BridgeResult>;
