// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendMoveWaypoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendMoveWaypoint'](arg1, arg2, arg3);
}

export function CancelMoveOrder(arg1) {
  return window['go']['main']['App']['CancelMoveOrder'](arg1);
}

export function DeleteScenario(arg1) {
  return window['go']['main']['App']['DeleteScenario'](arg1);
}

export function DeleteUnitDefinition(arg1) {
  return window['go']['main']['App']['DeleteUnitDefinition'](arg1);
}

export function GetScenario(arg1) {
  return window['go']['main']['App']['GetScenario'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListScenarios() {
  return window['go']['main']['App']['ListScenarios']();
}

export function ListUnitDefinitions() {
  return window['go']['main']['App']['ListUnitDefinitions']();
}

export function ListWeaponDefinitions() {
  return window['go']['main']['App']['ListWeaponDefinitions']();
}

export function LoadScenarioFromProto(arg1) {
  return window['go']['main']['App']['LoadScenarioFromProto'](arg1);
}

export function MoveUnit(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveUnit'](arg1, arg2, arg3);
}

export function PauseSim(arg1) {
  return window['go']['main']['App']['PauseSim'](arg1);
}

export function RemoveMoveWaypoint(arg1, arg2) {
  return window['go']['main']['App']['RemoveMoveWaypoint'](arg1, arg2);
}

export function RequestSync() {
  return window['go']['main']['App']['RequestSync']();
}

export function SaveScenario(arg1) {
  return window['go']['main']['App']['SaveScenario'](arg1);
}

export function SaveUnitDefinition(arg1) {
  return window['go']['main']['App']['SaveUnitDefinition'](arg1);
}

export function SetCountryRelationship(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetCountryRelationship'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetIntelSharing(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIntelSharing'](arg1, arg2, arg3);
}

export function SetSimSpeed(arg1) {
  return window['go']['main']['App']['SetSimSpeed'](arg1);
}

export function SetUnitAttackOrder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetUnitAttackOrder'](arg1, arg2, arg3, arg4, arg5);
}

export function SetUnitEngagement(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetUnitEngagement'](arg1, arg2, arg3);
}

export function UpdateMoveWaypoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMoveWaypoint'](arg1, arg2, arg3, arg4);
}
