// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListScenarios() {
  return window['go']['main']['App']['ListScenarios']();
}

export function LoadScenarioFromProto(arg1) {
  return window['go']['main']['App']['LoadScenarioFromProto'](arg1);
}

export function PauseSim(arg1) {
  return window['go']['main']['App']['PauseSim'](arg1);
}

export function RequestSync() {
  return window['go']['main']['App']['RequestSync']();
}

export function SetSimSpeed(arg1) {
  return window['go']['main']['App']['SetSimSpeed'](arg1);
}
