// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelMoveOrder(arg1:string):Promise<main.BridgeResult>;

export function DeleteScenario(arg1:string):Promise<main.BridgeResult>;

export function DeleteUnitDefinition(arg1:string):Promise<main.BridgeResult>;

export function GetScenario(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function ListScenarios():Promise<Array<Record<string, any>>>;

export function ListUnitDefinitions():Promise<Array<Record<string, any>>>;

export function ListWeaponDefinitions():Promise<Array<Record<string, any>>>;

export function LoadScenarioFromProto(arg1:string):Promise<main.BridgeResult>;

export function MoveUnit(arg1:string,arg2:number,arg3:number):Promise<main.BridgeResult>;

export function PauseSim(arg1:boolean):Promise<main.BridgeResult>;

export function RequestSync():Promise<main.BridgeResult>;

export function SaveScenario(arg1:string):Promise<main.BridgeResult>;

export function SaveUnitDefinition(arg1:string):Promise<main.BridgeResult>;

export function SetSimSpeed(arg1:number):Promise<main.BridgeResult>;
